package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ConsoleMock implements console.Console
type ConsoleMock struct {
	t minimock.Tester

	funcRunCmd          func(ctx context.Context, dir string, command string, commandParams ...string) (s1 string, err error)
	inspectFuncRunCmd   func(ctx context.Context, dir string, command string, commandParams ...string)
	afterRunCmdCounter  uint64
	beforeRunCmdCounter uint64
	RunCmdMock          mConsoleMockRunCmd
}

// NewConsoleMock returns a mock for console.Console
func NewConsoleMock(t minimock.Tester) *ConsoleMock {
	m := &ConsoleMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RunCmdMock = mConsoleMockRunCmd{mock: m}
	m.RunCmdMock.callArgs = []*ConsoleMockRunCmdParams{}

	return m
}

type mConsoleMockRunCmd struct {
	mock               *ConsoleMock
	defaultExpectation *ConsoleMockRunCmdExpectation
	expectations       []*ConsoleMockRunCmdExpectation

	callArgs []*ConsoleMockRunCmdParams
	mutex    sync.RWMutex
}

// ConsoleMockRunCmdExpectation specifies expectation struct of the Console.RunCmd
type ConsoleMockRunCmdExpectation struct {
	mock    *ConsoleMock
	params  *ConsoleMockRunCmdParams
	results *ConsoleMockRunCmdResults
	Counter uint64
}

// ConsoleMockRunCmdParams contains parameters of the Console.RunCmd
type ConsoleMockRunCmdParams struct {
	ctx           context.Context
	dir           string
	command       string
	commandParams []string
}

// ConsoleMockRunCmdResults contains results of the Console.RunCmd
type ConsoleMockRunCmdResults struct {
	s1  string
	err error
}

// Expect sets up expected params for Console.RunCmd
func (mmRunCmd *mConsoleMockRunCmd) Expect(ctx context.Context, dir string, command string, commandParams ...string) *mConsoleMockRunCmd {
	if mmRunCmd.mock.funcRunCmd != nil {
		mmRunCmd.mock.t.Fatalf("ConsoleMock.RunCmd mock is already set by Set")
	}

	if mmRunCmd.defaultExpectation == nil {
		mmRunCmd.defaultExpectation = &ConsoleMockRunCmdExpectation{}
	}

	mmRunCmd.defaultExpectation.params = &ConsoleMockRunCmdParams{ctx, dir, command, commandParams}
	for _, e := range mmRunCmd.expectations {
		if minimock.Equal(e.params, mmRunCmd.defaultExpectation.params) {
			mmRunCmd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRunCmd.defaultExpectation.params)
		}
	}

	return mmRunCmd
}

// Inspect accepts an inspector function that has same arguments as the Console.RunCmd
func (mmRunCmd *mConsoleMockRunCmd) Inspect(f func(ctx context.Context, dir string, command string, commandParams ...string)) *mConsoleMockRunCmd {
	if mmRunCmd.mock.inspectFuncRunCmd != nil {
		mmRunCmd.mock.t.Fatalf("Inspect function is already set for ConsoleMock.RunCmd")
	}

	mmRunCmd.mock.inspectFuncRunCmd = f

	return mmRunCmd
}

// Return sets up results that will be returned by Console.RunCmd
func (mmRunCmd *mConsoleMockRunCmd) Return(s1 string, err error) *ConsoleMock {
	if mmRunCmd.mock.funcRunCmd != nil {
		mmRunCmd.mock.t.Fatalf("ConsoleMock.RunCmd mock is already set by Set")
	}

	if mmRunCmd.defaultExpectation == nil {
		mmRunCmd.defaultExpectation = &ConsoleMockRunCmdExpectation{mock: mmRunCmd.mock}
	}
	mmRunCmd.defaultExpectation.results = &ConsoleMockRunCmdResults{s1, err}
	return mmRunCmd.mock
}

// Set uses given function f to mock the Console.RunCmd method
func (mmRunCmd *mConsoleMockRunCmd) Set(f func(ctx context.Context, dir string, command string, commandParams ...string) (s1 string, err error)) *ConsoleMock {
	if mmRunCmd.defaultExpectation != nil {
		mmRunCmd.mock.t.Fatalf("Default expectation is already set for the Console.RunCmd method")
	}

	if len(mmRunCmd.expectations) > 0 {
		mmRunCmd.mock.t.Fatalf("Some expectations are already set for the Console.RunCmd method")
	}

	mmRunCmd.mock.funcRunCmd = f
	return mmRunCmd.mock
}

// When sets expectation for the Console.RunCmd which will trigger the result defined by the following
// Then helper
func (mmRunCmd *mConsoleMockRunCmd) When(ctx context.Context, dir string, command string, commandParams ...string) *ConsoleMockRunCmdExpectation {
	if mmRunCmd.mock.funcRunCmd != nil {
		mmRunCmd.mock.t.Fatalf("ConsoleMock.RunCmd mock is already set by Set")
	}

	expectation := &ConsoleMockRunCmdExpectation{
		mock:   mmRunCmd.mock,
		params: &ConsoleMockRunCmdParams{ctx, dir, command, commandParams},
	}
	mmRunCmd.expectations = append(mmRunCmd.expectations, expectation)
	return expectation
}

// Then sets up Console.RunCmd return parameters for the expectation previously defined by the When method
func (e *ConsoleMockRunCmdExpectation) Then(s1 string, err error) *ConsoleMock {
	e.results = &ConsoleMockRunCmdResults{s1, err}
	return e.mock
}

// RunCmd implements console.Console
func (mmRunCmd *ConsoleMock) RunCmd(ctx context.Context, dir string, command string, commandParams ...string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmRunCmd.beforeRunCmdCounter, 1)
	defer mm_atomic.AddUint64(&mmRunCmd.afterRunCmdCounter, 1)

	if mmRunCmd.inspectFuncRunCmd != nil {
		mmRunCmd.inspectFuncRunCmd(ctx, dir, command, commandParams...)
	}

	mm_params := &ConsoleMockRunCmdParams{ctx, dir, command, commandParams}

	// Record call args
	mmRunCmd.RunCmdMock.mutex.Lock()
	mmRunCmd.RunCmdMock.callArgs = append(mmRunCmd.RunCmdMock.callArgs, mm_params)
	mmRunCmd.RunCmdMock.mutex.Unlock()

	for _, e := range mmRunCmd.RunCmdMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmRunCmd.RunCmdMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRunCmd.RunCmdMock.defaultExpectation.Counter, 1)
		mm_want := mmRunCmd.RunCmdMock.defaultExpectation.params
		mm_got := ConsoleMockRunCmdParams{ctx, dir, command, commandParams}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRunCmd.t.Errorf("ConsoleMock.RunCmd got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRunCmd.RunCmdMock.defaultExpectation.results
		if mm_results == nil {
			mmRunCmd.t.Fatal("No results are set for the ConsoleMock.RunCmd")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmRunCmd.funcRunCmd != nil {
		return mmRunCmd.funcRunCmd(ctx, dir, command, commandParams...)
	}
	mmRunCmd.t.Fatalf("Unexpected call to ConsoleMock.RunCmd. %v %v %v %v", ctx, dir, command, commandParams)
	return
}

// RunCmdAfterCounter returns a count of finished ConsoleMock.RunCmd invocations
func (mmRunCmd *ConsoleMock) RunCmdAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRunCmd.afterRunCmdCounter)
}

// RunCmdBeforeCounter returns a count of ConsoleMock.RunCmd invocations
func (mmRunCmd *ConsoleMock) RunCmdBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRunCmd.beforeRunCmdCounter)
}

// Calls returns a list of arguments used in each call to ConsoleMock.RunCmd.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRunCmd *mConsoleMockRunCmd) Calls() []*ConsoleMockRunCmdParams {
	mmRunCmd.mutex.RLock()

	argCopy := make([]*ConsoleMockRunCmdParams, len(mmRunCmd.callArgs))
	copy(argCopy, mmRunCmd.callArgs)

	mmRunCmd.mutex.RUnlock()

	return argCopy
}

// MinimockRunCmdDone returns true if the count of the RunCmd invocations corresponds
// the number of defined expectations
func (m *ConsoleMock) MinimockRunCmdDone() bool {
	for _, e := range m.RunCmdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RunCmdMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRunCmdCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRunCmd != nil && mm_atomic.LoadUint64(&m.afterRunCmdCounter) < 1 {
		return false
	}
	return true
}

// MinimockRunCmdInspect logs each unmet expectation
func (m *ConsoleMock) MinimockRunCmdInspect() {
	for _, e := range m.RunCmdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConsoleMock.RunCmd with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RunCmdMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRunCmdCounter) < 1 {
		if m.RunCmdMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ConsoleMock.RunCmd")
		} else {
			m.t.Errorf("Expected call to ConsoleMock.RunCmd with params: %#v", *m.RunCmdMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRunCmd != nil && mm_atomic.LoadUint64(&m.afterRunCmdCounter) < 1 {
		m.t.Error("Expected call to ConsoleMock.RunCmd")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ConsoleMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockRunCmdInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ConsoleMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ConsoleMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRunCmdDone()
}
