package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"iter"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"go.redsock.ru/moti/internal/models"
)

// ILockFileMock implements lockfile.ILockFile
type ILockFileMock struct {
	t minimock.Tester

	funcDepsIter          func() (p1 iter.Seq[models.LockFileInfo])
	inspectFuncDepsIter   func()
	afterDepsIterCounter  uint64
	beforeDepsIterCounter uint64
	DepsIterMock          mILockFileMockDepsIter

	funcIsEmpty          func() (b1 bool)
	inspectFuncIsEmpty   func()
	afterIsEmptyCounter  uint64
	beforeIsEmptyCounter uint64
	IsEmptyMock          mILockFileMockIsEmpty

	funcRead          func(moduleName string) (l1 models.LockFileInfo, err error)
	inspectFuncRead   func(moduleName string)
	afterReadCounter  uint64
	beforeReadCounter uint64
	ReadMock          mILockFileMockRead

	funcWrite          func(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash) (err error)
	inspectFuncWrite   func(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash)
	afterWriteCounter  uint64
	beforeWriteCounter uint64
	WriteMock          mILockFileMockWrite
}

// NewILockFileMock returns a mock for lockfile.ILockFile
func NewILockFileMock(t minimock.Tester) *ILockFileMock {
	m := &ILockFileMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DepsIterMock = mILockFileMockDepsIter{mock: m}

	m.IsEmptyMock = mILockFileMockIsEmpty{mock: m}

	m.ReadMock = mILockFileMockRead{mock: m}
	m.ReadMock.callArgs = []*ILockFileMockReadParams{}

	m.WriteMock = mILockFileMockWrite{mock: m}
	m.WriteMock.callArgs = []*ILockFileMockWriteParams{}

	return m
}

type mILockFileMockDepsIter struct {
	mock               *ILockFileMock
	defaultExpectation *ILockFileMockDepsIterExpectation
	expectations       []*ILockFileMockDepsIterExpectation
}

// ILockFileMockDepsIterExpectation specifies expectation struct of the ILockFile.DepsIter
type ILockFileMockDepsIterExpectation struct {
	mock *ILockFileMock

	results *ILockFileMockDepsIterResults
	Counter uint64
}

// ILockFileMockDepsIterResults contains results of the ILockFile.DepsIter
type ILockFileMockDepsIterResults struct {
	p1 iter.Seq[models.LockFileInfo]
}

// Expect sets up expected params for ILockFile.DepsIter
func (mmDepsIter *mILockFileMockDepsIter) Expect() *mILockFileMockDepsIter {
	if mmDepsIter.mock.funcDepsIter != nil {
		mmDepsIter.mock.t.Fatalf("ILockFileMock.DepsIter mock is already set by Set")
	}

	if mmDepsIter.defaultExpectation == nil {
		mmDepsIter.defaultExpectation = &ILockFileMockDepsIterExpectation{}
	}

	return mmDepsIter
}

// Inspect accepts an inspector function that has same arguments as the ILockFile.DepsIter
func (mmDepsIter *mILockFileMockDepsIter) Inspect(f func()) *mILockFileMockDepsIter {
	if mmDepsIter.mock.inspectFuncDepsIter != nil {
		mmDepsIter.mock.t.Fatalf("Inspect function is already set for ILockFileMock.DepsIter")
	}

	mmDepsIter.mock.inspectFuncDepsIter = f

	return mmDepsIter
}

// Return sets up results that will be returned by ILockFile.DepsIter
func (mmDepsIter *mILockFileMockDepsIter) Return(p1 iter.Seq[models.LockFileInfo]) *ILockFileMock {
	if mmDepsIter.mock.funcDepsIter != nil {
		mmDepsIter.mock.t.Fatalf("ILockFileMock.DepsIter mock is already set by Set")
	}

	if mmDepsIter.defaultExpectation == nil {
		mmDepsIter.defaultExpectation = &ILockFileMockDepsIterExpectation{mock: mmDepsIter.mock}
	}
	mmDepsIter.defaultExpectation.results = &ILockFileMockDepsIterResults{p1}
	return mmDepsIter.mock
}

// Set uses given function f to mock the ILockFile.DepsIter method
func (mmDepsIter *mILockFileMockDepsIter) Set(f func() (p1 iter.Seq[models.LockFileInfo])) *ILockFileMock {
	if mmDepsIter.defaultExpectation != nil {
		mmDepsIter.mock.t.Fatalf("Default expectation is already set for the ILockFile.DepsIter method")
	}

	if len(mmDepsIter.expectations) > 0 {
		mmDepsIter.mock.t.Fatalf("Some expectations are already set for the ILockFile.DepsIter method")
	}

	mmDepsIter.mock.funcDepsIter = f
	return mmDepsIter.mock
}

// DepsIter implements lockfile.ILockFile
func (mmDepsIter *ILockFileMock) DepsIter() (p1 iter.Seq[models.LockFileInfo]) {
	mm_atomic.AddUint64(&mmDepsIter.beforeDepsIterCounter, 1)
	defer mm_atomic.AddUint64(&mmDepsIter.afterDepsIterCounter, 1)

	if mmDepsIter.inspectFuncDepsIter != nil {
		mmDepsIter.inspectFuncDepsIter()
	}

	if mmDepsIter.DepsIterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDepsIter.DepsIterMock.defaultExpectation.Counter, 1)

		mm_results := mmDepsIter.DepsIterMock.defaultExpectation.results
		if mm_results == nil {
			mmDepsIter.t.Fatal("No results are set for the ILockFileMock.DepsIter")
		}
		return (*mm_results).p1
	}
	if mmDepsIter.funcDepsIter != nil {
		return mmDepsIter.funcDepsIter()
	}
	mmDepsIter.t.Fatalf("Unexpected call to ILockFileMock.DepsIter.")
	return
}

// DepsIterAfterCounter returns a count of finished ILockFileMock.DepsIter invocations
func (mmDepsIter *ILockFileMock) DepsIterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDepsIter.afterDepsIterCounter)
}

// DepsIterBeforeCounter returns a count of ILockFileMock.DepsIter invocations
func (mmDepsIter *ILockFileMock) DepsIterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDepsIter.beforeDepsIterCounter)
}

// MinimockDepsIterDone returns true if the count of the DepsIter invocations corresponds
// the number of defined expectations
func (m *ILockFileMock) MinimockDepsIterDone() bool {
	for _, e := range m.DepsIterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DepsIterMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDepsIterCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDepsIter != nil && mm_atomic.LoadUint64(&m.afterDepsIterCounter) < 1 {
		return false
	}
	return true
}

// MinimockDepsIterInspect logs each unmet expectation
func (m *ILockFileMock) MinimockDepsIterInspect() {
	for _, e := range m.DepsIterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to ILockFileMock.DepsIter")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DepsIterMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDepsIterCounter) < 1 {
		m.t.Error("Expected call to ILockFileMock.DepsIter")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDepsIter != nil && mm_atomic.LoadUint64(&m.afterDepsIterCounter) < 1 {
		m.t.Error("Expected call to ILockFileMock.DepsIter")
	}
}

type mILockFileMockIsEmpty struct {
	mock               *ILockFileMock
	defaultExpectation *ILockFileMockIsEmptyExpectation
	expectations       []*ILockFileMockIsEmptyExpectation
}

// ILockFileMockIsEmptyExpectation specifies expectation struct of the ILockFile.IsEmpty
type ILockFileMockIsEmptyExpectation struct {
	mock *ILockFileMock

	results *ILockFileMockIsEmptyResults
	Counter uint64
}

// ILockFileMockIsEmptyResults contains results of the ILockFile.IsEmpty
type ILockFileMockIsEmptyResults struct {
	b1 bool
}

// Expect sets up expected params for ILockFile.IsEmpty
func (mmIsEmpty *mILockFileMockIsEmpty) Expect() *mILockFileMockIsEmpty {
	if mmIsEmpty.mock.funcIsEmpty != nil {
		mmIsEmpty.mock.t.Fatalf("ILockFileMock.IsEmpty mock is already set by Set")
	}

	if mmIsEmpty.defaultExpectation == nil {
		mmIsEmpty.defaultExpectation = &ILockFileMockIsEmptyExpectation{}
	}

	return mmIsEmpty
}

// Inspect accepts an inspector function that has same arguments as the ILockFile.IsEmpty
func (mmIsEmpty *mILockFileMockIsEmpty) Inspect(f func()) *mILockFileMockIsEmpty {
	if mmIsEmpty.mock.inspectFuncIsEmpty != nil {
		mmIsEmpty.mock.t.Fatalf("Inspect function is already set for ILockFileMock.IsEmpty")
	}

	mmIsEmpty.mock.inspectFuncIsEmpty = f

	return mmIsEmpty
}

// Return sets up results that will be returned by ILockFile.IsEmpty
func (mmIsEmpty *mILockFileMockIsEmpty) Return(b1 bool) *ILockFileMock {
	if mmIsEmpty.mock.funcIsEmpty != nil {
		mmIsEmpty.mock.t.Fatalf("ILockFileMock.IsEmpty mock is already set by Set")
	}

	if mmIsEmpty.defaultExpectation == nil {
		mmIsEmpty.defaultExpectation = &ILockFileMockIsEmptyExpectation{mock: mmIsEmpty.mock}
	}
	mmIsEmpty.defaultExpectation.results = &ILockFileMockIsEmptyResults{b1}
	return mmIsEmpty.mock
}

// Set uses given function f to mock the ILockFile.IsEmpty method
func (mmIsEmpty *mILockFileMockIsEmpty) Set(f func() (b1 bool)) *ILockFileMock {
	if mmIsEmpty.defaultExpectation != nil {
		mmIsEmpty.mock.t.Fatalf("Default expectation is already set for the ILockFile.IsEmpty method")
	}

	if len(mmIsEmpty.expectations) > 0 {
		mmIsEmpty.mock.t.Fatalf("Some expectations are already set for the ILockFile.IsEmpty method")
	}

	mmIsEmpty.mock.funcIsEmpty = f
	return mmIsEmpty.mock
}

// IsEmpty implements lockfile.ILockFile
func (mmIsEmpty *ILockFileMock) IsEmpty() (b1 bool) {
	mm_atomic.AddUint64(&mmIsEmpty.beforeIsEmptyCounter, 1)
	defer mm_atomic.AddUint64(&mmIsEmpty.afterIsEmptyCounter, 1)

	if mmIsEmpty.inspectFuncIsEmpty != nil {
		mmIsEmpty.inspectFuncIsEmpty()
	}

	if mmIsEmpty.IsEmptyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIsEmpty.IsEmptyMock.defaultExpectation.Counter, 1)

		mm_results := mmIsEmpty.IsEmptyMock.defaultExpectation.results
		if mm_results == nil {
			mmIsEmpty.t.Fatal("No results are set for the ILockFileMock.IsEmpty")
		}
		return (*mm_results).b1
	}
	if mmIsEmpty.funcIsEmpty != nil {
		return mmIsEmpty.funcIsEmpty()
	}
	mmIsEmpty.t.Fatalf("Unexpected call to ILockFileMock.IsEmpty.")
	return
}

// IsEmptyAfterCounter returns a count of finished ILockFileMock.IsEmpty invocations
func (mmIsEmpty *ILockFileMock) IsEmptyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsEmpty.afterIsEmptyCounter)
}

// IsEmptyBeforeCounter returns a count of ILockFileMock.IsEmpty invocations
func (mmIsEmpty *ILockFileMock) IsEmptyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsEmpty.beforeIsEmptyCounter)
}

// MinimockIsEmptyDone returns true if the count of the IsEmpty invocations corresponds
// the number of defined expectations
func (m *ILockFileMock) MinimockIsEmptyDone() bool {
	for _, e := range m.IsEmptyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.IsEmptyMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterIsEmptyCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIsEmpty != nil && mm_atomic.LoadUint64(&m.afterIsEmptyCounter) < 1 {
		return false
	}
	return true
}

// MinimockIsEmptyInspect logs each unmet expectation
func (m *ILockFileMock) MinimockIsEmptyInspect() {
	for _, e := range m.IsEmptyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to ILockFileMock.IsEmpty")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.IsEmptyMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterIsEmptyCounter) < 1 {
		m.t.Error("Expected call to ILockFileMock.IsEmpty")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIsEmpty != nil && mm_atomic.LoadUint64(&m.afterIsEmptyCounter) < 1 {
		m.t.Error("Expected call to ILockFileMock.IsEmpty")
	}
}

type mILockFileMockRead struct {
	mock               *ILockFileMock
	defaultExpectation *ILockFileMockReadExpectation
	expectations       []*ILockFileMockReadExpectation

	callArgs []*ILockFileMockReadParams
	mutex    sync.RWMutex
}

// ILockFileMockReadExpectation specifies expectation struct of the ILockFile.Read
type ILockFileMockReadExpectation struct {
	mock    *ILockFileMock
	params  *ILockFileMockReadParams
	results *ILockFileMockReadResults
	Counter uint64
}

// ILockFileMockReadParams contains parameters of the ILockFile.Read
type ILockFileMockReadParams struct {
	moduleName string
}

// ILockFileMockReadResults contains results of the ILockFile.Read
type ILockFileMockReadResults struct {
	l1  models.LockFileInfo
	err error
}

// Expect sets up expected params for ILockFile.Read
func (mmRead *mILockFileMockRead) Expect(moduleName string) *mILockFileMockRead {
	if mmRead.mock.funcRead != nil {
		mmRead.mock.t.Fatalf("ILockFileMock.Read mock is already set by Set")
	}

	if mmRead.defaultExpectation == nil {
		mmRead.defaultExpectation = &ILockFileMockReadExpectation{}
	}

	mmRead.defaultExpectation.params = &ILockFileMockReadParams{moduleName}
	for _, e := range mmRead.expectations {
		if minimock.Equal(e.params, mmRead.defaultExpectation.params) {
			mmRead.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRead.defaultExpectation.params)
		}
	}

	return mmRead
}

// Inspect accepts an inspector function that has same arguments as the ILockFile.Read
func (mmRead *mILockFileMockRead) Inspect(f func(moduleName string)) *mILockFileMockRead {
	if mmRead.mock.inspectFuncRead != nil {
		mmRead.mock.t.Fatalf("Inspect function is already set for ILockFileMock.Read")
	}

	mmRead.mock.inspectFuncRead = f

	return mmRead
}

// Return sets up results that will be returned by ILockFile.Read
func (mmRead *mILockFileMockRead) Return(l1 models.LockFileInfo, err error) *ILockFileMock {
	if mmRead.mock.funcRead != nil {
		mmRead.mock.t.Fatalf("ILockFileMock.Read mock is already set by Set")
	}

	if mmRead.defaultExpectation == nil {
		mmRead.defaultExpectation = &ILockFileMockReadExpectation{mock: mmRead.mock}
	}
	mmRead.defaultExpectation.results = &ILockFileMockReadResults{l1, err}
	return mmRead.mock
}

// Set uses given function f to mock the ILockFile.Read method
func (mmRead *mILockFileMockRead) Set(f func(moduleName string) (l1 models.LockFileInfo, err error)) *ILockFileMock {
	if mmRead.defaultExpectation != nil {
		mmRead.mock.t.Fatalf("Default expectation is already set for the ILockFile.Read method")
	}

	if len(mmRead.expectations) > 0 {
		mmRead.mock.t.Fatalf("Some expectations are already set for the ILockFile.Read method")
	}

	mmRead.mock.funcRead = f
	return mmRead.mock
}

// When sets expectation for the ILockFile.Read which will trigger the result defined by the following
// Then helper
func (mmRead *mILockFileMockRead) When(moduleName string) *ILockFileMockReadExpectation {
	if mmRead.mock.funcRead != nil {
		mmRead.mock.t.Fatalf("ILockFileMock.Read mock is already set by Set")
	}

	expectation := &ILockFileMockReadExpectation{
		mock:   mmRead.mock,
		params: &ILockFileMockReadParams{moduleName},
	}
	mmRead.expectations = append(mmRead.expectations, expectation)
	return expectation
}

// Then sets up ILockFile.Read return parameters for the expectation previously defined by the When method
func (e *ILockFileMockReadExpectation) Then(l1 models.LockFileInfo, err error) *ILockFileMock {
	e.results = &ILockFileMockReadResults{l1, err}
	return e.mock
}

// Read implements lockfile.ILockFile
func (mmRead *ILockFileMock) Read(moduleName string) (l1 models.LockFileInfo, err error) {
	mm_atomic.AddUint64(&mmRead.beforeReadCounter, 1)
	defer mm_atomic.AddUint64(&mmRead.afterReadCounter, 1)

	if mmRead.inspectFuncRead != nil {
		mmRead.inspectFuncRead(moduleName)
	}

	mm_params := &ILockFileMockReadParams{moduleName}

	// Record call args
	mmRead.ReadMock.mutex.Lock()
	mmRead.ReadMock.callArgs = append(mmRead.ReadMock.callArgs, mm_params)
	mmRead.ReadMock.mutex.Unlock()

	for _, e := range mmRead.ReadMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.l1, e.results.err
		}
	}

	if mmRead.ReadMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRead.ReadMock.defaultExpectation.Counter, 1)
		mm_want := mmRead.ReadMock.defaultExpectation.params
		mm_got := ILockFileMockReadParams{moduleName}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRead.t.Errorf("ILockFileMock.Read got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRead.ReadMock.defaultExpectation.results
		if mm_results == nil {
			mmRead.t.Fatal("No results are set for the ILockFileMock.Read")
		}
		return (*mm_results).l1, (*mm_results).err
	}
	if mmRead.funcRead != nil {
		return mmRead.funcRead(moduleName)
	}
	mmRead.t.Fatalf("Unexpected call to ILockFileMock.Read. %v", moduleName)
	return
}

// ReadAfterCounter returns a count of finished ILockFileMock.Read invocations
func (mmRead *ILockFileMock) ReadAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRead.afterReadCounter)
}

// ReadBeforeCounter returns a count of ILockFileMock.Read invocations
func (mmRead *ILockFileMock) ReadBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRead.beforeReadCounter)
}

// Calls returns a list of arguments used in each call to ILockFileMock.Read.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRead *mILockFileMockRead) Calls() []*ILockFileMockReadParams {
	mmRead.mutex.RLock()

	argCopy := make([]*ILockFileMockReadParams, len(mmRead.callArgs))
	copy(argCopy, mmRead.callArgs)

	mmRead.mutex.RUnlock()

	return argCopy
}

// MinimockReadDone returns true if the count of the Read invocations corresponds
// the number of defined expectations
func (m *ILockFileMock) MinimockReadDone() bool {
	for _, e := range m.ReadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRead != nil && mm_atomic.LoadUint64(&m.afterReadCounter) < 1 {
		return false
	}
	return true
}

// MinimockReadInspect logs each unmet expectation
func (m *ILockFileMock) MinimockReadInspect() {
	for _, e := range m.ReadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ILockFileMock.Read with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadCounter) < 1 {
		if m.ReadMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ILockFileMock.Read")
		} else {
			m.t.Errorf("Expected call to ILockFileMock.Read with params: %#v", *m.ReadMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRead != nil && mm_atomic.LoadUint64(&m.afterReadCounter) < 1 {
		m.t.Error("Expected call to ILockFileMock.Read")
	}
}

type mILockFileMockWrite struct {
	mock               *ILockFileMock
	defaultExpectation *ILockFileMockWriteExpectation
	expectations       []*ILockFileMockWriteExpectation

	callArgs []*ILockFileMockWriteParams
	mutex    sync.RWMutex
}

// ILockFileMockWriteExpectation specifies expectation struct of the ILockFile.Write
type ILockFileMockWriteExpectation struct {
	mock    *ILockFileMock
	params  *ILockFileMockWriteParams
	results *ILockFileMockWriteResults
	Counter uint64
}

// ILockFileMockWriteParams contains parameters of the ILockFile.Write
type ILockFileMockWriteParams struct {
	moduleName           string
	revisionVersion      string
	installedPackageHash models.ModuleHash
}

// ILockFileMockWriteResults contains results of the ILockFile.Write
type ILockFileMockWriteResults struct {
	err error
}

// Expect sets up expected params for ILockFile.Write
func (mmWrite *mILockFileMockWrite) Expect(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash) *mILockFileMockWrite {
	if mmWrite.mock.funcWrite != nil {
		mmWrite.mock.t.Fatalf("ILockFileMock.Write mock is already set by Set")
	}

	if mmWrite.defaultExpectation == nil {
		mmWrite.defaultExpectation = &ILockFileMockWriteExpectation{}
	}

	mmWrite.defaultExpectation.params = &ILockFileMockWriteParams{moduleName, revisionVersion, installedPackageHash}
	for _, e := range mmWrite.expectations {
		if minimock.Equal(e.params, mmWrite.defaultExpectation.params) {
			mmWrite.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWrite.defaultExpectation.params)
		}
	}

	return mmWrite
}

// Inspect accepts an inspector function that has same arguments as the ILockFile.Write
func (mmWrite *mILockFileMockWrite) Inspect(f func(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash)) *mILockFileMockWrite {
	if mmWrite.mock.inspectFuncWrite != nil {
		mmWrite.mock.t.Fatalf("Inspect function is already set for ILockFileMock.Write")
	}

	mmWrite.mock.inspectFuncWrite = f

	return mmWrite
}

// Return sets up results that will be returned by ILockFile.Write
func (mmWrite *mILockFileMockWrite) Return(err error) *ILockFileMock {
	if mmWrite.mock.funcWrite != nil {
		mmWrite.mock.t.Fatalf("ILockFileMock.Write mock is already set by Set")
	}

	if mmWrite.defaultExpectation == nil {
		mmWrite.defaultExpectation = &ILockFileMockWriteExpectation{mock: mmWrite.mock}
	}
	mmWrite.defaultExpectation.results = &ILockFileMockWriteResults{err}
	return mmWrite.mock
}

// Set uses given function f to mock the ILockFile.Write method
func (mmWrite *mILockFileMockWrite) Set(f func(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash) (err error)) *ILockFileMock {
	if mmWrite.defaultExpectation != nil {
		mmWrite.mock.t.Fatalf("Default expectation is already set for the ILockFile.Write method")
	}

	if len(mmWrite.expectations) > 0 {
		mmWrite.mock.t.Fatalf("Some expectations are already set for the ILockFile.Write method")
	}

	mmWrite.mock.funcWrite = f
	return mmWrite.mock
}

// When sets expectation for the ILockFile.Write which will trigger the result defined by the following
// Then helper
func (mmWrite *mILockFileMockWrite) When(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash) *ILockFileMockWriteExpectation {
	if mmWrite.mock.funcWrite != nil {
		mmWrite.mock.t.Fatalf("ILockFileMock.Write mock is already set by Set")
	}

	expectation := &ILockFileMockWriteExpectation{
		mock:   mmWrite.mock,
		params: &ILockFileMockWriteParams{moduleName, revisionVersion, installedPackageHash},
	}
	mmWrite.expectations = append(mmWrite.expectations, expectation)
	return expectation
}

// Then sets up ILockFile.Write return parameters for the expectation previously defined by the When method
func (e *ILockFileMockWriteExpectation) Then(err error) *ILockFileMock {
	e.results = &ILockFileMockWriteResults{err}
	return e.mock
}

// Write implements lockfile.ILockFile
func (mmWrite *ILockFileMock) Write(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash) (err error) {
	mm_atomic.AddUint64(&mmWrite.beforeWriteCounter, 1)
	defer mm_atomic.AddUint64(&mmWrite.afterWriteCounter, 1)

	if mmWrite.inspectFuncWrite != nil {
		mmWrite.inspectFuncWrite(moduleName, revisionVersion, installedPackageHash)
	}

	mm_params := &ILockFileMockWriteParams{moduleName, revisionVersion, installedPackageHash}

	// Record call args
	mmWrite.WriteMock.mutex.Lock()
	mmWrite.WriteMock.callArgs = append(mmWrite.WriteMock.callArgs, mm_params)
	mmWrite.WriteMock.mutex.Unlock()

	for _, e := range mmWrite.WriteMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmWrite.WriteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWrite.WriteMock.defaultExpectation.Counter, 1)
		mm_want := mmWrite.WriteMock.defaultExpectation.params
		mm_got := ILockFileMockWriteParams{moduleName, revisionVersion, installedPackageHash}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWrite.t.Errorf("ILockFileMock.Write got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWrite.WriteMock.defaultExpectation.results
		if mm_results == nil {
			mmWrite.t.Fatal("No results are set for the ILockFileMock.Write")
		}
		return (*mm_results).err
	}
	if mmWrite.funcWrite != nil {
		return mmWrite.funcWrite(moduleName, revisionVersion, installedPackageHash)
	}
	mmWrite.t.Fatalf("Unexpected call to ILockFileMock.Write. %v %v %v", moduleName, revisionVersion, installedPackageHash)
	return
}

// WriteAfterCounter returns a count of finished ILockFileMock.Write invocations
func (mmWrite *ILockFileMock) WriteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWrite.afterWriteCounter)
}

// WriteBeforeCounter returns a count of ILockFileMock.Write invocations
func (mmWrite *ILockFileMock) WriteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWrite.beforeWriteCounter)
}

// Calls returns a list of arguments used in each call to ILockFileMock.Write.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWrite *mILockFileMockWrite) Calls() []*ILockFileMockWriteParams {
	mmWrite.mutex.RLock()

	argCopy := make([]*ILockFileMockWriteParams, len(mmWrite.callArgs))
	copy(argCopy, mmWrite.callArgs)

	mmWrite.mutex.RUnlock()

	return argCopy
}

// MinimockWriteDone returns true if the count of the Write invocations corresponds
// the number of defined expectations
func (m *ILockFileMock) MinimockWriteDone() bool {
	for _, e := range m.WriteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.WriteMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterWriteCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWrite != nil && mm_atomic.LoadUint64(&m.afterWriteCounter) < 1 {
		return false
	}
	return true
}

// MinimockWriteInspect logs each unmet expectation
func (m *ILockFileMock) MinimockWriteInspect() {
	for _, e := range m.WriteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ILockFileMock.Write with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.WriteMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterWriteCounter) < 1 {
		if m.WriteMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ILockFileMock.Write")
		} else {
			m.t.Errorf("Expected call to ILockFileMock.Write with params: %#v", *m.WriteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWrite != nil && mm_atomic.LoadUint64(&m.afterWriteCounter) < 1 {
		m.t.Error("Expected call to ILockFileMock.Write")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ILockFileMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockDepsIterInspect()

		m.MinimockIsEmptyInspect()

		m.MinimockReadInspect()

		m.MinimockWriteInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ILockFileMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ILockFileMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDepsIterDone() &&
		m.MinimockIsEmptyDone() &&
		m.MinimockReadDone() &&
		m.MinimockWriteDone()
}
