package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"go.redsock.ru/moti/internal/adapters/repository"
	"go.redsock.ru/moti/internal/models"
)

// IModuleConfigMock implements moduleconfig.IModuleConfig
type IModuleConfigMock struct {
	t minimock.Tester

	funcReadFromRepo          func(ctx context.Context, repo repository.Repo, revision models.Revision) (m1 models.ModuleConfig, err error)
	inspectFuncReadFromRepo   func(ctx context.Context, repo repository.Repo, revision models.Revision)
	afterReadFromRepoCounter  uint64
	beforeReadFromRepoCounter uint64
	ReadFromRepoMock          mIModuleConfigMockReadFromRepo
}

// NewIModuleConfigMock returns a mock for moduleconfig.IModuleConfig
func NewIModuleConfigMock(t minimock.Tester) *IModuleConfigMock {
	m := &IModuleConfigMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ReadFromRepoMock = mIModuleConfigMockReadFromRepo{mock: m}
	m.ReadFromRepoMock.callArgs = []*IModuleConfigMockReadFromRepoParams{}

	return m
}

type mIModuleConfigMockReadFromRepo struct {
	mock               *IModuleConfigMock
	defaultExpectation *IModuleConfigMockReadFromRepoExpectation
	expectations       []*IModuleConfigMockReadFromRepoExpectation

	callArgs []*IModuleConfigMockReadFromRepoParams
	mutex    sync.RWMutex
}

// IModuleConfigMockReadFromRepoExpectation specifies expectation struct of the IModuleConfig.ReadFromRepo
type IModuleConfigMockReadFromRepoExpectation struct {
	mock    *IModuleConfigMock
	params  *IModuleConfigMockReadFromRepoParams
	results *IModuleConfigMockReadFromRepoResults
	Counter uint64
}

// IModuleConfigMockReadFromRepoParams contains parameters of the IModuleConfig.ReadFromRepo
type IModuleConfigMockReadFromRepoParams struct {
	ctx      context.Context
	repo     repository.Repo
	revision models.Revision
}

// IModuleConfigMockReadFromRepoResults contains results of the IModuleConfig.ReadFromRepo
type IModuleConfigMockReadFromRepoResults struct {
	m1  models.ModuleConfig
	err error
}

// Expect sets up expected params for IModuleConfig.ReadFromRepo
func (mmReadFromRepo *mIModuleConfigMockReadFromRepo) Expect(ctx context.Context, repo repository.Repo, revision models.Revision) *mIModuleConfigMockReadFromRepo {
	if mmReadFromRepo.mock.funcReadFromRepo != nil {
		mmReadFromRepo.mock.t.Fatalf("IModuleConfigMock.ReadFromRepo mock is already set by Set")
	}

	if mmReadFromRepo.defaultExpectation == nil {
		mmReadFromRepo.defaultExpectation = &IModuleConfigMockReadFromRepoExpectation{}
	}

	mmReadFromRepo.defaultExpectation.params = &IModuleConfigMockReadFromRepoParams{ctx, repo, revision}
	for _, e := range mmReadFromRepo.expectations {
		if minimock.Equal(e.params, mmReadFromRepo.defaultExpectation.params) {
			mmReadFromRepo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmReadFromRepo.defaultExpectation.params)
		}
	}

	return mmReadFromRepo
}

// Inspect accepts an inspector function that has same arguments as the IModuleConfig.ReadFromRepo
func (mmReadFromRepo *mIModuleConfigMockReadFromRepo) Inspect(f func(ctx context.Context, repo repository.Repo, revision models.Revision)) *mIModuleConfigMockReadFromRepo {
	if mmReadFromRepo.mock.inspectFuncReadFromRepo != nil {
		mmReadFromRepo.mock.t.Fatalf("Inspect function is already set for IModuleConfigMock.ReadFromRepo")
	}

	mmReadFromRepo.mock.inspectFuncReadFromRepo = f

	return mmReadFromRepo
}

// Return sets up results that will be returned by IModuleConfig.ReadFromRepo
func (mmReadFromRepo *mIModuleConfigMockReadFromRepo) Return(m1 models.ModuleConfig, err error) *IModuleConfigMock {
	if mmReadFromRepo.mock.funcReadFromRepo != nil {
		mmReadFromRepo.mock.t.Fatalf("IModuleConfigMock.ReadFromRepo mock is already set by Set")
	}

	if mmReadFromRepo.defaultExpectation == nil {
		mmReadFromRepo.defaultExpectation = &IModuleConfigMockReadFromRepoExpectation{mock: mmReadFromRepo.mock}
	}
	mmReadFromRepo.defaultExpectation.results = &IModuleConfigMockReadFromRepoResults{m1, err}
	return mmReadFromRepo.mock
}

// Set uses given function f to mock the IModuleConfig.ReadFromRepo method
func (mmReadFromRepo *mIModuleConfigMockReadFromRepo) Set(f func(ctx context.Context, repo repository.Repo, revision models.Revision) (m1 models.ModuleConfig, err error)) *IModuleConfigMock {
	if mmReadFromRepo.defaultExpectation != nil {
		mmReadFromRepo.mock.t.Fatalf("Default expectation is already set for the IModuleConfig.ReadFromRepo method")
	}

	if len(mmReadFromRepo.expectations) > 0 {
		mmReadFromRepo.mock.t.Fatalf("Some expectations are already set for the IModuleConfig.ReadFromRepo method")
	}

	mmReadFromRepo.mock.funcReadFromRepo = f
	return mmReadFromRepo.mock
}

// When sets expectation for the IModuleConfig.ReadFromRepo which will trigger the result defined by the following
// Then helper
func (mmReadFromRepo *mIModuleConfigMockReadFromRepo) When(ctx context.Context, repo repository.Repo, revision models.Revision) *IModuleConfigMockReadFromRepoExpectation {
	if mmReadFromRepo.mock.funcReadFromRepo != nil {
		mmReadFromRepo.mock.t.Fatalf("IModuleConfigMock.ReadFromRepo mock is already set by Set")
	}

	expectation := &IModuleConfigMockReadFromRepoExpectation{
		mock:   mmReadFromRepo.mock,
		params: &IModuleConfigMockReadFromRepoParams{ctx, repo, revision},
	}
	mmReadFromRepo.expectations = append(mmReadFromRepo.expectations, expectation)
	return expectation
}

// Then sets up IModuleConfig.ReadFromRepo return parameters for the expectation previously defined by the When method
func (e *IModuleConfigMockReadFromRepoExpectation) Then(m1 models.ModuleConfig, err error) *IModuleConfigMock {
	e.results = &IModuleConfigMockReadFromRepoResults{m1, err}
	return e.mock
}

// ReadFromRepo implements moduleconfig.IModuleConfig
func (mmReadFromRepo *IModuleConfigMock) ReadFromRepo(ctx context.Context, repo repository.Repo, revision models.Revision) (m1 models.ModuleConfig, err error) {
	mm_atomic.AddUint64(&mmReadFromRepo.beforeReadFromRepoCounter, 1)
	defer mm_atomic.AddUint64(&mmReadFromRepo.afterReadFromRepoCounter, 1)

	if mmReadFromRepo.inspectFuncReadFromRepo != nil {
		mmReadFromRepo.inspectFuncReadFromRepo(ctx, repo, revision)
	}

	mm_params := &IModuleConfigMockReadFromRepoParams{ctx, repo, revision}

	// Record call args
	mmReadFromRepo.ReadFromRepoMock.mutex.Lock()
	mmReadFromRepo.ReadFromRepoMock.callArgs = append(mmReadFromRepo.ReadFromRepoMock.callArgs, mm_params)
	mmReadFromRepo.ReadFromRepoMock.mutex.Unlock()

	for _, e := range mmReadFromRepo.ReadFromRepoMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmReadFromRepo.ReadFromRepoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReadFromRepo.ReadFromRepoMock.defaultExpectation.Counter, 1)
		mm_want := mmReadFromRepo.ReadFromRepoMock.defaultExpectation.params
		mm_got := IModuleConfigMockReadFromRepoParams{ctx, repo, revision}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmReadFromRepo.t.Errorf("IModuleConfigMock.ReadFromRepo got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmReadFromRepo.ReadFromRepoMock.defaultExpectation.results
		if mm_results == nil {
			mmReadFromRepo.t.Fatal("No results are set for the IModuleConfigMock.ReadFromRepo")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmReadFromRepo.funcReadFromRepo != nil {
		return mmReadFromRepo.funcReadFromRepo(ctx, repo, revision)
	}
	mmReadFromRepo.t.Fatalf("Unexpected call to IModuleConfigMock.ReadFromRepo. %v %v %v", ctx, repo, revision)
	return
}

// ReadFromRepoAfterCounter returns a count of finished IModuleConfigMock.ReadFromRepo invocations
func (mmReadFromRepo *IModuleConfigMock) ReadFromRepoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReadFromRepo.afterReadFromRepoCounter)
}

// ReadFromRepoBeforeCounter returns a count of IModuleConfigMock.ReadFromRepo invocations
func (mmReadFromRepo *IModuleConfigMock) ReadFromRepoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReadFromRepo.beforeReadFromRepoCounter)
}

// Calls returns a list of arguments used in each call to IModuleConfigMock.ReadFromRepo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmReadFromRepo *mIModuleConfigMockReadFromRepo) Calls() []*IModuleConfigMockReadFromRepoParams {
	mmReadFromRepo.mutex.RLock()

	argCopy := make([]*IModuleConfigMockReadFromRepoParams, len(mmReadFromRepo.callArgs))
	copy(argCopy, mmReadFromRepo.callArgs)

	mmReadFromRepo.mutex.RUnlock()

	return argCopy
}

// MinimockReadFromRepoDone returns true if the count of the ReadFromRepo invocations corresponds
// the number of defined expectations
func (m *IModuleConfigMock) MinimockReadFromRepoDone() bool {
	for _, e := range m.ReadFromRepoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadFromRepoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadFromRepoCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReadFromRepo != nil && mm_atomic.LoadUint64(&m.afterReadFromRepoCounter) < 1 {
		return false
	}
	return true
}

// MinimockReadFromRepoInspect logs each unmet expectation
func (m *IModuleConfigMock) MinimockReadFromRepoInspect() {
	for _, e := range m.ReadFromRepoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IModuleConfigMock.ReadFromRepo with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadFromRepoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadFromRepoCounter) < 1 {
		if m.ReadFromRepoMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IModuleConfigMock.ReadFromRepo")
		} else {
			m.t.Errorf("Expected call to IModuleConfigMock.ReadFromRepo with params: %#v", *m.ReadFromRepoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReadFromRepo != nil && mm_atomic.LoadUint64(&m.afterReadFromRepoCounter) < 1 {
		m.t.Error("Expected call to IModuleConfigMock.ReadFromRepo")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IModuleConfigMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockReadFromRepoInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IModuleConfigMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IModuleConfigMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockReadFromRepoDone()
}
