package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"go.redsock.ru/moti/internal/models"
)

// IStorageMock implements storage.IStorage
type IStorageMock struct {
	t minimock.Tester

	funcCreateCacheDownloadDir          func(c1 models.CacheDownloadPaths) (err error)
	inspectFuncCreateCacheDownloadDir   func(c1 models.CacheDownloadPaths)
	afterCreateCacheDownloadDirCounter  uint64
	beforeCreateCacheDownloadDirCounter uint64
	CreateCacheDownloadDirMock          mIStorageMockCreateCacheDownloadDir

	funcCreateCacheRepositoryDir          func(name string) (s1 string, err error)
	inspectFuncCreateCacheRepositoryDir   func(name string)
	afterCreateCacheRepositoryDirCounter  uint64
	beforeCreateCacheRepositoryDirCounter uint64
	CreateCacheRepositoryDirMock          mIStorageMockCreateCacheRepositoryDir

	funcGetCacheDownloadPaths          func(module models.Module, revision models.Revision) (c1 models.CacheDownloadPaths)
	inspectFuncGetCacheDownloadPaths   func(module models.Module, revision models.Revision)
	afterGetCacheDownloadPathsCounter  uint64
	beforeGetCacheDownloadPathsCounter uint64
	GetCacheDownloadPathsMock          mIStorageMockGetCacheDownloadPaths

	funcGetInstallDir          func(moduleName string, revisionVersion string) (s1 string)
	inspectFuncGetInstallDir   func(moduleName string, revisionVersion string)
	afterGetInstallDirCounter  uint64
	beforeGetInstallDirCounter uint64
	GetInstallDirMock          mIStorageMockGetInstallDir

	funcGetInstalledModuleHash          func(moduleName string, revisionVersion string) (m1 models.ModuleHash, err error)
	inspectFuncGetInstalledModuleHash   func(moduleName string, revisionVersion string)
	afterGetInstalledModuleHashCounter  uint64
	beforeGetInstalledModuleHashCounter uint64
	GetInstalledModuleHashMock          mIStorageMockGetInstalledModuleHash

	funcInstall          func(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig) (m1 models.ModuleHash, err error)
	inspectFuncInstall   func(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig)
	afterInstallCounter  uint64
	beforeInstallCounter uint64
	InstallMock          mIStorageMockInstall

	funcIsModuleInstalled          func(module models.Module) (b1 bool, err error)
	inspectFuncIsModuleInstalled   func(module models.Module)
	afterIsModuleInstalledCounter  uint64
	beforeIsModuleInstalledCounter uint64
	IsModuleInstalledMock          mIStorageMockIsModuleInstalled
}

// NewIStorageMock returns a mock for storage.IStorage
func NewIStorageMock(t minimock.Tester) *IStorageMock {
	m := &IStorageMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateCacheDownloadDirMock = mIStorageMockCreateCacheDownloadDir{mock: m}
	m.CreateCacheDownloadDirMock.callArgs = []*IStorageMockCreateCacheDownloadDirParams{}

	m.CreateCacheRepositoryDirMock = mIStorageMockCreateCacheRepositoryDir{mock: m}
	m.CreateCacheRepositoryDirMock.callArgs = []*IStorageMockCreateCacheRepositoryDirParams{}

	m.GetCacheDownloadPathsMock = mIStorageMockGetCacheDownloadPaths{mock: m}
	m.GetCacheDownloadPathsMock.callArgs = []*IStorageMockGetCacheDownloadPathsParams{}

	m.GetInstallDirMock = mIStorageMockGetInstallDir{mock: m}
	m.GetInstallDirMock.callArgs = []*IStorageMockGetInstallDirParams{}

	m.GetInstalledModuleHashMock = mIStorageMockGetInstalledModuleHash{mock: m}
	m.GetInstalledModuleHashMock.callArgs = []*IStorageMockGetInstalledModuleHashParams{}

	m.InstallMock = mIStorageMockInstall{mock: m}
	m.InstallMock.callArgs = []*IStorageMockInstallParams{}

	m.IsModuleInstalledMock = mIStorageMockIsModuleInstalled{mock: m}
	m.IsModuleInstalledMock.callArgs = []*IStorageMockIsModuleInstalledParams{}

	return m
}

type mIStorageMockCreateCacheDownloadDir struct {
	mock               *IStorageMock
	defaultExpectation *IStorageMockCreateCacheDownloadDirExpectation
	expectations       []*IStorageMockCreateCacheDownloadDirExpectation

	callArgs []*IStorageMockCreateCacheDownloadDirParams
	mutex    sync.RWMutex
}

// IStorageMockCreateCacheDownloadDirExpectation specifies expectation struct of the IStorage.CreateCacheDownloadDir
type IStorageMockCreateCacheDownloadDirExpectation struct {
	mock    *IStorageMock
	params  *IStorageMockCreateCacheDownloadDirParams
	results *IStorageMockCreateCacheDownloadDirResults
	Counter uint64
}

// IStorageMockCreateCacheDownloadDirParams contains parameters of the IStorage.CreateCacheDownloadDir
type IStorageMockCreateCacheDownloadDirParams struct {
	c1 models.CacheDownloadPaths
}

// IStorageMockCreateCacheDownloadDirResults contains results of the IStorage.CreateCacheDownloadDir
type IStorageMockCreateCacheDownloadDirResults struct {
	err error
}

// Expect sets up expected params for IStorage.CreateCacheDownloadDir
func (mmCreateCacheDownloadDir *mIStorageMockCreateCacheDownloadDir) Expect(c1 models.CacheDownloadPaths) *mIStorageMockCreateCacheDownloadDir {
	if mmCreateCacheDownloadDir.mock.funcCreateCacheDownloadDir != nil {
		mmCreateCacheDownloadDir.mock.t.Fatalf("IStorageMock.CreateCacheDownloadDir mock is already set by Set")
	}

	if mmCreateCacheDownloadDir.defaultExpectation == nil {
		mmCreateCacheDownloadDir.defaultExpectation = &IStorageMockCreateCacheDownloadDirExpectation{}
	}

	mmCreateCacheDownloadDir.defaultExpectation.params = &IStorageMockCreateCacheDownloadDirParams{c1}
	for _, e := range mmCreateCacheDownloadDir.expectations {
		if minimock.Equal(e.params, mmCreateCacheDownloadDir.defaultExpectation.params) {
			mmCreateCacheDownloadDir.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateCacheDownloadDir.defaultExpectation.params)
		}
	}

	return mmCreateCacheDownloadDir
}

// Inspect accepts an inspector function that has same arguments as the IStorage.CreateCacheDownloadDir
func (mmCreateCacheDownloadDir *mIStorageMockCreateCacheDownloadDir) Inspect(f func(c1 models.CacheDownloadPaths)) *mIStorageMockCreateCacheDownloadDir {
	if mmCreateCacheDownloadDir.mock.inspectFuncCreateCacheDownloadDir != nil {
		mmCreateCacheDownloadDir.mock.t.Fatalf("Inspect function is already set for IStorageMock.CreateCacheDownloadDir")
	}

	mmCreateCacheDownloadDir.mock.inspectFuncCreateCacheDownloadDir = f

	return mmCreateCacheDownloadDir
}

// Return sets up results that will be returned by IStorage.CreateCacheDownloadDir
func (mmCreateCacheDownloadDir *mIStorageMockCreateCacheDownloadDir) Return(err error) *IStorageMock {
	if mmCreateCacheDownloadDir.mock.funcCreateCacheDownloadDir != nil {
		mmCreateCacheDownloadDir.mock.t.Fatalf("IStorageMock.CreateCacheDownloadDir mock is already set by Set")
	}

	if mmCreateCacheDownloadDir.defaultExpectation == nil {
		mmCreateCacheDownloadDir.defaultExpectation = &IStorageMockCreateCacheDownloadDirExpectation{mock: mmCreateCacheDownloadDir.mock}
	}
	mmCreateCacheDownloadDir.defaultExpectation.results = &IStorageMockCreateCacheDownloadDirResults{err}
	return mmCreateCacheDownloadDir.mock
}

// Set uses given function f to mock the IStorage.CreateCacheDownloadDir method
func (mmCreateCacheDownloadDir *mIStorageMockCreateCacheDownloadDir) Set(f func(c1 models.CacheDownloadPaths) (err error)) *IStorageMock {
	if mmCreateCacheDownloadDir.defaultExpectation != nil {
		mmCreateCacheDownloadDir.mock.t.Fatalf("Default expectation is already set for the IStorage.CreateCacheDownloadDir method")
	}

	if len(mmCreateCacheDownloadDir.expectations) > 0 {
		mmCreateCacheDownloadDir.mock.t.Fatalf("Some expectations are already set for the IStorage.CreateCacheDownloadDir method")
	}

	mmCreateCacheDownloadDir.mock.funcCreateCacheDownloadDir = f
	return mmCreateCacheDownloadDir.mock
}

// When sets expectation for the IStorage.CreateCacheDownloadDir which will trigger the result defined by the following
// Then helper
func (mmCreateCacheDownloadDir *mIStorageMockCreateCacheDownloadDir) When(c1 models.CacheDownloadPaths) *IStorageMockCreateCacheDownloadDirExpectation {
	if mmCreateCacheDownloadDir.mock.funcCreateCacheDownloadDir != nil {
		mmCreateCacheDownloadDir.mock.t.Fatalf("IStorageMock.CreateCacheDownloadDir mock is already set by Set")
	}

	expectation := &IStorageMockCreateCacheDownloadDirExpectation{
		mock:   mmCreateCacheDownloadDir.mock,
		params: &IStorageMockCreateCacheDownloadDirParams{c1},
	}
	mmCreateCacheDownloadDir.expectations = append(mmCreateCacheDownloadDir.expectations, expectation)
	return expectation
}

// Then sets up IStorage.CreateCacheDownloadDir return parameters for the expectation previously defined by the When method
func (e *IStorageMockCreateCacheDownloadDirExpectation) Then(err error) *IStorageMock {
	e.results = &IStorageMockCreateCacheDownloadDirResults{err}
	return e.mock
}

// CreateCacheDownloadDir implements storage.IStorage
func (mmCreateCacheDownloadDir *IStorageMock) CreateCacheDownloadDir(c1 models.CacheDownloadPaths) (err error) {
	mm_atomic.AddUint64(&mmCreateCacheDownloadDir.beforeCreateCacheDownloadDirCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateCacheDownloadDir.afterCreateCacheDownloadDirCounter, 1)

	if mmCreateCacheDownloadDir.inspectFuncCreateCacheDownloadDir != nil {
		mmCreateCacheDownloadDir.inspectFuncCreateCacheDownloadDir(c1)
	}

	mm_params := &IStorageMockCreateCacheDownloadDirParams{c1}

	// Record call args
	mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.mutex.Lock()
	mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.callArgs = append(mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.callArgs, mm_params)
	mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.mutex.Unlock()

	for _, e := range mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.defaultExpectation.params
		mm_got := IStorageMockCreateCacheDownloadDirParams{c1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateCacheDownloadDir.t.Errorf("IStorageMock.CreateCacheDownloadDir got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateCacheDownloadDir.CreateCacheDownloadDirMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateCacheDownloadDir.t.Fatal("No results are set for the IStorageMock.CreateCacheDownloadDir")
		}
		return (*mm_results).err
	}
	if mmCreateCacheDownloadDir.funcCreateCacheDownloadDir != nil {
		return mmCreateCacheDownloadDir.funcCreateCacheDownloadDir(c1)
	}
	mmCreateCacheDownloadDir.t.Fatalf("Unexpected call to IStorageMock.CreateCacheDownloadDir. %v", c1)
	return
}

// CreateCacheDownloadDirAfterCounter returns a count of finished IStorageMock.CreateCacheDownloadDir invocations
func (mmCreateCacheDownloadDir *IStorageMock) CreateCacheDownloadDirAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateCacheDownloadDir.afterCreateCacheDownloadDirCounter)
}

// CreateCacheDownloadDirBeforeCounter returns a count of IStorageMock.CreateCacheDownloadDir invocations
func (mmCreateCacheDownloadDir *IStorageMock) CreateCacheDownloadDirBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateCacheDownloadDir.beforeCreateCacheDownloadDirCounter)
}

// Calls returns a list of arguments used in each call to IStorageMock.CreateCacheDownloadDir.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateCacheDownloadDir *mIStorageMockCreateCacheDownloadDir) Calls() []*IStorageMockCreateCacheDownloadDirParams {
	mmCreateCacheDownloadDir.mutex.RLock()

	argCopy := make([]*IStorageMockCreateCacheDownloadDirParams, len(mmCreateCacheDownloadDir.callArgs))
	copy(argCopy, mmCreateCacheDownloadDir.callArgs)

	mmCreateCacheDownloadDir.mutex.RUnlock()

	return argCopy
}

// MinimockCreateCacheDownloadDirDone returns true if the count of the CreateCacheDownloadDir invocations corresponds
// the number of defined expectations
func (m *IStorageMock) MinimockCreateCacheDownloadDirDone() bool {
	for _, e := range m.CreateCacheDownloadDirMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateCacheDownloadDirMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCacheDownloadDirCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateCacheDownloadDir != nil && mm_atomic.LoadUint64(&m.afterCreateCacheDownloadDirCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateCacheDownloadDirInspect logs each unmet expectation
func (m *IStorageMock) MinimockCreateCacheDownloadDirInspect() {
	for _, e := range m.CreateCacheDownloadDirMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IStorageMock.CreateCacheDownloadDir with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateCacheDownloadDirMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCacheDownloadDirCounter) < 1 {
		if m.CreateCacheDownloadDirMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IStorageMock.CreateCacheDownloadDir")
		} else {
			m.t.Errorf("Expected call to IStorageMock.CreateCacheDownloadDir with params: %#v", *m.CreateCacheDownloadDirMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateCacheDownloadDir != nil && mm_atomic.LoadUint64(&m.afterCreateCacheDownloadDirCounter) < 1 {
		m.t.Error("Expected call to IStorageMock.CreateCacheDownloadDir")
	}
}

type mIStorageMockCreateCacheRepositoryDir struct {
	mock               *IStorageMock
	defaultExpectation *IStorageMockCreateCacheRepositoryDirExpectation
	expectations       []*IStorageMockCreateCacheRepositoryDirExpectation

	callArgs []*IStorageMockCreateCacheRepositoryDirParams
	mutex    sync.RWMutex
}

// IStorageMockCreateCacheRepositoryDirExpectation specifies expectation struct of the IStorage.CreateCacheRepositoryDir
type IStorageMockCreateCacheRepositoryDirExpectation struct {
	mock    *IStorageMock
	params  *IStorageMockCreateCacheRepositoryDirParams
	results *IStorageMockCreateCacheRepositoryDirResults
	Counter uint64
}

// IStorageMockCreateCacheRepositoryDirParams contains parameters of the IStorage.CreateCacheRepositoryDir
type IStorageMockCreateCacheRepositoryDirParams struct {
	name string
}

// IStorageMockCreateCacheRepositoryDirResults contains results of the IStorage.CreateCacheRepositoryDir
type IStorageMockCreateCacheRepositoryDirResults struct {
	s1  string
	err error
}

// Expect sets up expected params for IStorage.CreateCacheRepositoryDir
func (mmCreateCacheRepositoryDir *mIStorageMockCreateCacheRepositoryDir) Expect(name string) *mIStorageMockCreateCacheRepositoryDir {
	if mmCreateCacheRepositoryDir.mock.funcCreateCacheRepositoryDir != nil {
		mmCreateCacheRepositoryDir.mock.t.Fatalf("IStorageMock.CreateCacheRepositoryDir mock is already set by Set")
	}

	if mmCreateCacheRepositoryDir.defaultExpectation == nil {
		mmCreateCacheRepositoryDir.defaultExpectation = &IStorageMockCreateCacheRepositoryDirExpectation{}
	}

	mmCreateCacheRepositoryDir.defaultExpectation.params = &IStorageMockCreateCacheRepositoryDirParams{name}
	for _, e := range mmCreateCacheRepositoryDir.expectations {
		if minimock.Equal(e.params, mmCreateCacheRepositoryDir.defaultExpectation.params) {
			mmCreateCacheRepositoryDir.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateCacheRepositoryDir.defaultExpectation.params)
		}
	}

	return mmCreateCacheRepositoryDir
}

// Inspect accepts an inspector function that has same arguments as the IStorage.CreateCacheRepositoryDir
func (mmCreateCacheRepositoryDir *mIStorageMockCreateCacheRepositoryDir) Inspect(f func(name string)) *mIStorageMockCreateCacheRepositoryDir {
	if mmCreateCacheRepositoryDir.mock.inspectFuncCreateCacheRepositoryDir != nil {
		mmCreateCacheRepositoryDir.mock.t.Fatalf("Inspect function is already set for IStorageMock.CreateCacheRepositoryDir")
	}

	mmCreateCacheRepositoryDir.mock.inspectFuncCreateCacheRepositoryDir = f

	return mmCreateCacheRepositoryDir
}

// Return sets up results that will be returned by IStorage.CreateCacheRepositoryDir
func (mmCreateCacheRepositoryDir *mIStorageMockCreateCacheRepositoryDir) Return(s1 string, err error) *IStorageMock {
	if mmCreateCacheRepositoryDir.mock.funcCreateCacheRepositoryDir != nil {
		mmCreateCacheRepositoryDir.mock.t.Fatalf("IStorageMock.CreateCacheRepositoryDir mock is already set by Set")
	}

	if mmCreateCacheRepositoryDir.defaultExpectation == nil {
		mmCreateCacheRepositoryDir.defaultExpectation = &IStorageMockCreateCacheRepositoryDirExpectation{mock: mmCreateCacheRepositoryDir.mock}
	}
	mmCreateCacheRepositoryDir.defaultExpectation.results = &IStorageMockCreateCacheRepositoryDirResults{s1, err}
	return mmCreateCacheRepositoryDir.mock
}

// Set uses given function f to mock the IStorage.CreateCacheRepositoryDir method
func (mmCreateCacheRepositoryDir *mIStorageMockCreateCacheRepositoryDir) Set(f func(name string) (s1 string, err error)) *IStorageMock {
	if mmCreateCacheRepositoryDir.defaultExpectation != nil {
		mmCreateCacheRepositoryDir.mock.t.Fatalf("Default expectation is already set for the IStorage.CreateCacheRepositoryDir method")
	}

	if len(mmCreateCacheRepositoryDir.expectations) > 0 {
		mmCreateCacheRepositoryDir.mock.t.Fatalf("Some expectations are already set for the IStorage.CreateCacheRepositoryDir method")
	}

	mmCreateCacheRepositoryDir.mock.funcCreateCacheRepositoryDir = f
	return mmCreateCacheRepositoryDir.mock
}

// When sets expectation for the IStorage.CreateCacheRepositoryDir which will trigger the result defined by the following
// Then helper
func (mmCreateCacheRepositoryDir *mIStorageMockCreateCacheRepositoryDir) When(name string) *IStorageMockCreateCacheRepositoryDirExpectation {
	if mmCreateCacheRepositoryDir.mock.funcCreateCacheRepositoryDir != nil {
		mmCreateCacheRepositoryDir.mock.t.Fatalf("IStorageMock.CreateCacheRepositoryDir mock is already set by Set")
	}

	expectation := &IStorageMockCreateCacheRepositoryDirExpectation{
		mock:   mmCreateCacheRepositoryDir.mock,
		params: &IStorageMockCreateCacheRepositoryDirParams{name},
	}
	mmCreateCacheRepositoryDir.expectations = append(mmCreateCacheRepositoryDir.expectations, expectation)
	return expectation
}

// Then sets up IStorage.CreateCacheRepositoryDir return parameters for the expectation previously defined by the When method
func (e *IStorageMockCreateCacheRepositoryDirExpectation) Then(s1 string, err error) *IStorageMock {
	e.results = &IStorageMockCreateCacheRepositoryDirResults{s1, err}
	return e.mock
}

// CreateCacheRepositoryDir implements storage.IStorage
func (mmCreateCacheRepositoryDir *IStorageMock) CreateCacheRepositoryDir(name string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmCreateCacheRepositoryDir.beforeCreateCacheRepositoryDirCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateCacheRepositoryDir.afterCreateCacheRepositoryDirCounter, 1)

	if mmCreateCacheRepositoryDir.inspectFuncCreateCacheRepositoryDir != nil {
		mmCreateCacheRepositoryDir.inspectFuncCreateCacheRepositoryDir(name)
	}

	mm_params := &IStorageMockCreateCacheRepositoryDirParams{name}

	// Record call args
	mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.mutex.Lock()
	mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.callArgs = append(mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.callArgs, mm_params)
	mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.mutex.Unlock()

	for _, e := range mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.defaultExpectation.params
		mm_got := IStorageMockCreateCacheRepositoryDirParams{name}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateCacheRepositoryDir.t.Errorf("IStorageMock.CreateCacheRepositoryDir got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateCacheRepositoryDir.CreateCacheRepositoryDirMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateCacheRepositoryDir.t.Fatal("No results are set for the IStorageMock.CreateCacheRepositoryDir")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmCreateCacheRepositoryDir.funcCreateCacheRepositoryDir != nil {
		return mmCreateCacheRepositoryDir.funcCreateCacheRepositoryDir(name)
	}
	mmCreateCacheRepositoryDir.t.Fatalf("Unexpected call to IStorageMock.CreateCacheRepositoryDir. %v", name)
	return
}

// CreateCacheRepositoryDirAfterCounter returns a count of finished IStorageMock.CreateCacheRepositoryDir invocations
func (mmCreateCacheRepositoryDir *IStorageMock) CreateCacheRepositoryDirAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateCacheRepositoryDir.afterCreateCacheRepositoryDirCounter)
}

// CreateCacheRepositoryDirBeforeCounter returns a count of IStorageMock.CreateCacheRepositoryDir invocations
func (mmCreateCacheRepositoryDir *IStorageMock) CreateCacheRepositoryDirBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateCacheRepositoryDir.beforeCreateCacheRepositoryDirCounter)
}

// Calls returns a list of arguments used in each call to IStorageMock.CreateCacheRepositoryDir.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateCacheRepositoryDir *mIStorageMockCreateCacheRepositoryDir) Calls() []*IStorageMockCreateCacheRepositoryDirParams {
	mmCreateCacheRepositoryDir.mutex.RLock()

	argCopy := make([]*IStorageMockCreateCacheRepositoryDirParams, len(mmCreateCacheRepositoryDir.callArgs))
	copy(argCopy, mmCreateCacheRepositoryDir.callArgs)

	mmCreateCacheRepositoryDir.mutex.RUnlock()

	return argCopy
}

// MinimockCreateCacheRepositoryDirDone returns true if the count of the CreateCacheRepositoryDir invocations corresponds
// the number of defined expectations
func (m *IStorageMock) MinimockCreateCacheRepositoryDirDone() bool {
	for _, e := range m.CreateCacheRepositoryDirMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateCacheRepositoryDirMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCacheRepositoryDirCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateCacheRepositoryDir != nil && mm_atomic.LoadUint64(&m.afterCreateCacheRepositoryDirCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateCacheRepositoryDirInspect logs each unmet expectation
func (m *IStorageMock) MinimockCreateCacheRepositoryDirInspect() {
	for _, e := range m.CreateCacheRepositoryDirMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IStorageMock.CreateCacheRepositoryDir with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateCacheRepositoryDirMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCacheRepositoryDirCounter) < 1 {
		if m.CreateCacheRepositoryDirMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IStorageMock.CreateCacheRepositoryDir")
		} else {
			m.t.Errorf("Expected call to IStorageMock.CreateCacheRepositoryDir with params: %#v", *m.CreateCacheRepositoryDirMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateCacheRepositoryDir != nil && mm_atomic.LoadUint64(&m.afterCreateCacheRepositoryDirCounter) < 1 {
		m.t.Error("Expected call to IStorageMock.CreateCacheRepositoryDir")
	}
}

type mIStorageMockGetCacheDownloadPaths struct {
	mock               *IStorageMock
	defaultExpectation *IStorageMockGetCacheDownloadPathsExpectation
	expectations       []*IStorageMockGetCacheDownloadPathsExpectation

	callArgs []*IStorageMockGetCacheDownloadPathsParams
	mutex    sync.RWMutex
}

// IStorageMockGetCacheDownloadPathsExpectation specifies expectation struct of the IStorage.GetCacheDownloadPaths
type IStorageMockGetCacheDownloadPathsExpectation struct {
	mock    *IStorageMock
	params  *IStorageMockGetCacheDownloadPathsParams
	results *IStorageMockGetCacheDownloadPathsResults
	Counter uint64
}

// IStorageMockGetCacheDownloadPathsParams contains parameters of the IStorage.GetCacheDownloadPaths
type IStorageMockGetCacheDownloadPathsParams struct {
	module   models.Module
	revision models.Revision
}

// IStorageMockGetCacheDownloadPathsResults contains results of the IStorage.GetCacheDownloadPaths
type IStorageMockGetCacheDownloadPathsResults struct {
	c1 models.CacheDownloadPaths
}

// Expect sets up expected params for IStorage.GetCacheDownloadPaths
func (mmGetCacheDownloadPaths *mIStorageMockGetCacheDownloadPaths) Expect(module models.Module, revision models.Revision) *mIStorageMockGetCacheDownloadPaths {
	if mmGetCacheDownloadPaths.mock.funcGetCacheDownloadPaths != nil {
		mmGetCacheDownloadPaths.mock.t.Fatalf("IStorageMock.GetCacheDownloadPaths mock is already set by Set")
	}

	if mmGetCacheDownloadPaths.defaultExpectation == nil {
		mmGetCacheDownloadPaths.defaultExpectation = &IStorageMockGetCacheDownloadPathsExpectation{}
	}

	mmGetCacheDownloadPaths.defaultExpectation.params = &IStorageMockGetCacheDownloadPathsParams{module, revision}
	for _, e := range mmGetCacheDownloadPaths.expectations {
		if minimock.Equal(e.params, mmGetCacheDownloadPaths.defaultExpectation.params) {
			mmGetCacheDownloadPaths.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetCacheDownloadPaths.defaultExpectation.params)
		}
	}

	return mmGetCacheDownloadPaths
}

// Inspect accepts an inspector function that has same arguments as the IStorage.GetCacheDownloadPaths
func (mmGetCacheDownloadPaths *mIStorageMockGetCacheDownloadPaths) Inspect(f func(module models.Module, revision models.Revision)) *mIStorageMockGetCacheDownloadPaths {
	if mmGetCacheDownloadPaths.mock.inspectFuncGetCacheDownloadPaths != nil {
		mmGetCacheDownloadPaths.mock.t.Fatalf("Inspect function is already set for IStorageMock.GetCacheDownloadPaths")
	}

	mmGetCacheDownloadPaths.mock.inspectFuncGetCacheDownloadPaths = f

	return mmGetCacheDownloadPaths
}

// Return sets up results that will be returned by IStorage.GetCacheDownloadPaths
func (mmGetCacheDownloadPaths *mIStorageMockGetCacheDownloadPaths) Return(c1 models.CacheDownloadPaths) *IStorageMock {
	if mmGetCacheDownloadPaths.mock.funcGetCacheDownloadPaths != nil {
		mmGetCacheDownloadPaths.mock.t.Fatalf("IStorageMock.GetCacheDownloadPaths mock is already set by Set")
	}

	if mmGetCacheDownloadPaths.defaultExpectation == nil {
		mmGetCacheDownloadPaths.defaultExpectation = &IStorageMockGetCacheDownloadPathsExpectation{mock: mmGetCacheDownloadPaths.mock}
	}
	mmGetCacheDownloadPaths.defaultExpectation.results = &IStorageMockGetCacheDownloadPathsResults{c1}
	return mmGetCacheDownloadPaths.mock
}

// Set uses given function f to mock the IStorage.GetCacheDownloadPaths method
func (mmGetCacheDownloadPaths *mIStorageMockGetCacheDownloadPaths) Set(f func(module models.Module, revision models.Revision) (c1 models.CacheDownloadPaths)) *IStorageMock {
	if mmGetCacheDownloadPaths.defaultExpectation != nil {
		mmGetCacheDownloadPaths.mock.t.Fatalf("Default expectation is already set for the IStorage.GetCacheDownloadPaths method")
	}

	if len(mmGetCacheDownloadPaths.expectations) > 0 {
		mmGetCacheDownloadPaths.mock.t.Fatalf("Some expectations are already set for the IStorage.GetCacheDownloadPaths method")
	}

	mmGetCacheDownloadPaths.mock.funcGetCacheDownloadPaths = f
	return mmGetCacheDownloadPaths.mock
}

// When sets expectation for the IStorage.GetCacheDownloadPaths which will trigger the result defined by the following
// Then helper
func (mmGetCacheDownloadPaths *mIStorageMockGetCacheDownloadPaths) When(module models.Module, revision models.Revision) *IStorageMockGetCacheDownloadPathsExpectation {
	if mmGetCacheDownloadPaths.mock.funcGetCacheDownloadPaths != nil {
		mmGetCacheDownloadPaths.mock.t.Fatalf("IStorageMock.GetCacheDownloadPaths mock is already set by Set")
	}

	expectation := &IStorageMockGetCacheDownloadPathsExpectation{
		mock:   mmGetCacheDownloadPaths.mock,
		params: &IStorageMockGetCacheDownloadPathsParams{module, revision},
	}
	mmGetCacheDownloadPaths.expectations = append(mmGetCacheDownloadPaths.expectations, expectation)
	return expectation
}

// Then sets up IStorage.GetCacheDownloadPaths return parameters for the expectation previously defined by the When method
func (e *IStorageMockGetCacheDownloadPathsExpectation) Then(c1 models.CacheDownloadPaths) *IStorageMock {
	e.results = &IStorageMockGetCacheDownloadPathsResults{c1}
	return e.mock
}

// GetCacheDownloadPaths implements storage.IStorage
func (mmGetCacheDownloadPaths *IStorageMock) GetCacheDownloadPaths(module models.Module, revision models.Revision) (c1 models.CacheDownloadPaths) {
	mm_atomic.AddUint64(&mmGetCacheDownloadPaths.beforeGetCacheDownloadPathsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetCacheDownloadPaths.afterGetCacheDownloadPathsCounter, 1)

	if mmGetCacheDownloadPaths.inspectFuncGetCacheDownloadPaths != nil {
		mmGetCacheDownloadPaths.inspectFuncGetCacheDownloadPaths(module, revision)
	}

	mm_params := &IStorageMockGetCacheDownloadPathsParams{module, revision}

	// Record call args
	mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.mutex.Lock()
	mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.callArgs = append(mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.callArgs, mm_params)
	mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.mutex.Unlock()

	for _, e := range mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c1
		}
	}

	if mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.defaultExpectation.params
		mm_got := IStorageMockGetCacheDownloadPathsParams{module, revision}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetCacheDownloadPaths.t.Errorf("IStorageMock.GetCacheDownloadPaths got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetCacheDownloadPaths.GetCacheDownloadPathsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetCacheDownloadPaths.t.Fatal("No results are set for the IStorageMock.GetCacheDownloadPaths")
		}
		return (*mm_results).c1
	}
	if mmGetCacheDownloadPaths.funcGetCacheDownloadPaths != nil {
		return mmGetCacheDownloadPaths.funcGetCacheDownloadPaths(module, revision)
	}
	mmGetCacheDownloadPaths.t.Fatalf("Unexpected call to IStorageMock.GetCacheDownloadPaths. %v %v", module, revision)
	return
}

// GetCacheDownloadPathsAfterCounter returns a count of finished IStorageMock.GetCacheDownloadPaths invocations
func (mmGetCacheDownloadPaths *IStorageMock) GetCacheDownloadPathsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCacheDownloadPaths.afterGetCacheDownloadPathsCounter)
}

// GetCacheDownloadPathsBeforeCounter returns a count of IStorageMock.GetCacheDownloadPaths invocations
func (mmGetCacheDownloadPaths *IStorageMock) GetCacheDownloadPathsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetCacheDownloadPaths.beforeGetCacheDownloadPathsCounter)
}

// Calls returns a list of arguments used in each call to IStorageMock.GetCacheDownloadPaths.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetCacheDownloadPaths *mIStorageMockGetCacheDownloadPaths) Calls() []*IStorageMockGetCacheDownloadPathsParams {
	mmGetCacheDownloadPaths.mutex.RLock()

	argCopy := make([]*IStorageMockGetCacheDownloadPathsParams, len(mmGetCacheDownloadPaths.callArgs))
	copy(argCopy, mmGetCacheDownloadPaths.callArgs)

	mmGetCacheDownloadPaths.mutex.RUnlock()

	return argCopy
}

// MinimockGetCacheDownloadPathsDone returns true if the count of the GetCacheDownloadPaths invocations corresponds
// the number of defined expectations
func (m *IStorageMock) MinimockGetCacheDownloadPathsDone() bool {
	for _, e := range m.GetCacheDownloadPathsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetCacheDownloadPathsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCacheDownloadPathsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetCacheDownloadPaths != nil && mm_atomic.LoadUint64(&m.afterGetCacheDownloadPathsCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetCacheDownloadPathsInspect logs each unmet expectation
func (m *IStorageMock) MinimockGetCacheDownloadPathsInspect() {
	for _, e := range m.GetCacheDownloadPathsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IStorageMock.GetCacheDownloadPaths with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetCacheDownloadPathsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCacheDownloadPathsCounter) < 1 {
		if m.GetCacheDownloadPathsMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IStorageMock.GetCacheDownloadPaths")
		} else {
			m.t.Errorf("Expected call to IStorageMock.GetCacheDownloadPaths with params: %#v", *m.GetCacheDownloadPathsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetCacheDownloadPaths != nil && mm_atomic.LoadUint64(&m.afterGetCacheDownloadPathsCounter) < 1 {
		m.t.Error("Expected call to IStorageMock.GetCacheDownloadPaths")
	}
}

type mIStorageMockGetInstallDir struct {
	mock               *IStorageMock
	defaultExpectation *IStorageMockGetInstallDirExpectation
	expectations       []*IStorageMockGetInstallDirExpectation

	callArgs []*IStorageMockGetInstallDirParams
	mutex    sync.RWMutex
}

// IStorageMockGetInstallDirExpectation specifies expectation struct of the IStorage.GetInstallDir
type IStorageMockGetInstallDirExpectation struct {
	mock    *IStorageMock
	params  *IStorageMockGetInstallDirParams
	results *IStorageMockGetInstallDirResults
	Counter uint64
}

// IStorageMockGetInstallDirParams contains parameters of the IStorage.GetInstallDir
type IStorageMockGetInstallDirParams struct {
	moduleName      string
	revisionVersion string
}

// IStorageMockGetInstallDirResults contains results of the IStorage.GetInstallDir
type IStorageMockGetInstallDirResults struct {
	s1 string
}

// Expect sets up expected params for IStorage.GetInstallDir
func (mmGetInstallDir *mIStorageMockGetInstallDir) Expect(moduleName string, revisionVersion string) *mIStorageMockGetInstallDir {
	if mmGetInstallDir.mock.funcGetInstallDir != nil {
		mmGetInstallDir.mock.t.Fatalf("IStorageMock.GetInstallDir mock is already set by Set")
	}

	if mmGetInstallDir.defaultExpectation == nil {
		mmGetInstallDir.defaultExpectation = &IStorageMockGetInstallDirExpectation{}
	}

	mmGetInstallDir.defaultExpectation.params = &IStorageMockGetInstallDirParams{moduleName, revisionVersion}
	for _, e := range mmGetInstallDir.expectations {
		if minimock.Equal(e.params, mmGetInstallDir.defaultExpectation.params) {
			mmGetInstallDir.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetInstallDir.defaultExpectation.params)
		}
	}

	return mmGetInstallDir
}

// Inspect accepts an inspector function that has same arguments as the IStorage.GetInstallDir
func (mmGetInstallDir *mIStorageMockGetInstallDir) Inspect(f func(moduleName string, revisionVersion string)) *mIStorageMockGetInstallDir {
	if mmGetInstallDir.mock.inspectFuncGetInstallDir != nil {
		mmGetInstallDir.mock.t.Fatalf("Inspect function is already set for IStorageMock.GetInstallDir")
	}

	mmGetInstallDir.mock.inspectFuncGetInstallDir = f

	return mmGetInstallDir
}

// Return sets up results that will be returned by IStorage.GetInstallDir
func (mmGetInstallDir *mIStorageMockGetInstallDir) Return(s1 string) *IStorageMock {
	if mmGetInstallDir.mock.funcGetInstallDir != nil {
		mmGetInstallDir.mock.t.Fatalf("IStorageMock.GetInstallDir mock is already set by Set")
	}

	if mmGetInstallDir.defaultExpectation == nil {
		mmGetInstallDir.defaultExpectation = &IStorageMockGetInstallDirExpectation{mock: mmGetInstallDir.mock}
	}
	mmGetInstallDir.defaultExpectation.results = &IStorageMockGetInstallDirResults{s1}
	return mmGetInstallDir.mock
}

// Set uses given function f to mock the IStorage.GetInstallDir method
func (mmGetInstallDir *mIStorageMockGetInstallDir) Set(f func(moduleName string, revisionVersion string) (s1 string)) *IStorageMock {
	if mmGetInstallDir.defaultExpectation != nil {
		mmGetInstallDir.mock.t.Fatalf("Default expectation is already set for the IStorage.GetInstallDir method")
	}

	if len(mmGetInstallDir.expectations) > 0 {
		mmGetInstallDir.mock.t.Fatalf("Some expectations are already set for the IStorage.GetInstallDir method")
	}

	mmGetInstallDir.mock.funcGetInstallDir = f
	return mmGetInstallDir.mock
}

// When sets expectation for the IStorage.GetInstallDir which will trigger the result defined by the following
// Then helper
func (mmGetInstallDir *mIStorageMockGetInstallDir) When(moduleName string, revisionVersion string) *IStorageMockGetInstallDirExpectation {
	if mmGetInstallDir.mock.funcGetInstallDir != nil {
		mmGetInstallDir.mock.t.Fatalf("IStorageMock.GetInstallDir mock is already set by Set")
	}

	expectation := &IStorageMockGetInstallDirExpectation{
		mock:   mmGetInstallDir.mock,
		params: &IStorageMockGetInstallDirParams{moduleName, revisionVersion},
	}
	mmGetInstallDir.expectations = append(mmGetInstallDir.expectations, expectation)
	return expectation
}

// Then sets up IStorage.GetInstallDir return parameters for the expectation previously defined by the When method
func (e *IStorageMockGetInstallDirExpectation) Then(s1 string) *IStorageMock {
	e.results = &IStorageMockGetInstallDirResults{s1}
	return e.mock
}

// GetInstallDir implements storage.IStorage
func (mmGetInstallDir *IStorageMock) GetInstallDir(moduleName string, revisionVersion string) (s1 string) {
	mm_atomic.AddUint64(&mmGetInstallDir.beforeGetInstallDirCounter, 1)
	defer mm_atomic.AddUint64(&mmGetInstallDir.afterGetInstallDirCounter, 1)

	if mmGetInstallDir.inspectFuncGetInstallDir != nil {
		mmGetInstallDir.inspectFuncGetInstallDir(moduleName, revisionVersion)
	}

	mm_params := &IStorageMockGetInstallDirParams{moduleName, revisionVersion}

	// Record call args
	mmGetInstallDir.GetInstallDirMock.mutex.Lock()
	mmGetInstallDir.GetInstallDirMock.callArgs = append(mmGetInstallDir.GetInstallDirMock.callArgs, mm_params)
	mmGetInstallDir.GetInstallDirMock.mutex.Unlock()

	for _, e := range mmGetInstallDir.GetInstallDirMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1
		}
	}

	if mmGetInstallDir.GetInstallDirMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetInstallDir.GetInstallDirMock.defaultExpectation.Counter, 1)
		mm_want := mmGetInstallDir.GetInstallDirMock.defaultExpectation.params
		mm_got := IStorageMockGetInstallDirParams{moduleName, revisionVersion}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetInstallDir.t.Errorf("IStorageMock.GetInstallDir got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetInstallDir.GetInstallDirMock.defaultExpectation.results
		if mm_results == nil {
			mmGetInstallDir.t.Fatal("No results are set for the IStorageMock.GetInstallDir")
		}
		return (*mm_results).s1
	}
	if mmGetInstallDir.funcGetInstallDir != nil {
		return mmGetInstallDir.funcGetInstallDir(moduleName, revisionVersion)
	}
	mmGetInstallDir.t.Fatalf("Unexpected call to IStorageMock.GetInstallDir. %v %v", moduleName, revisionVersion)
	return
}

// GetInstallDirAfterCounter returns a count of finished IStorageMock.GetInstallDir invocations
func (mmGetInstallDir *IStorageMock) GetInstallDirAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInstallDir.afterGetInstallDirCounter)
}

// GetInstallDirBeforeCounter returns a count of IStorageMock.GetInstallDir invocations
func (mmGetInstallDir *IStorageMock) GetInstallDirBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInstallDir.beforeGetInstallDirCounter)
}

// Calls returns a list of arguments used in each call to IStorageMock.GetInstallDir.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetInstallDir *mIStorageMockGetInstallDir) Calls() []*IStorageMockGetInstallDirParams {
	mmGetInstallDir.mutex.RLock()

	argCopy := make([]*IStorageMockGetInstallDirParams, len(mmGetInstallDir.callArgs))
	copy(argCopy, mmGetInstallDir.callArgs)

	mmGetInstallDir.mutex.RUnlock()

	return argCopy
}

// MinimockGetInstallDirDone returns true if the count of the GetInstallDir invocations corresponds
// the number of defined expectations
func (m *IStorageMock) MinimockGetInstallDirDone() bool {
	for _, e := range m.GetInstallDirMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetInstallDirMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetInstallDirCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetInstallDir != nil && mm_atomic.LoadUint64(&m.afterGetInstallDirCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetInstallDirInspect logs each unmet expectation
func (m *IStorageMock) MinimockGetInstallDirInspect() {
	for _, e := range m.GetInstallDirMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IStorageMock.GetInstallDir with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetInstallDirMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetInstallDirCounter) < 1 {
		if m.GetInstallDirMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IStorageMock.GetInstallDir")
		} else {
			m.t.Errorf("Expected call to IStorageMock.GetInstallDir with params: %#v", *m.GetInstallDirMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetInstallDir != nil && mm_atomic.LoadUint64(&m.afterGetInstallDirCounter) < 1 {
		m.t.Error("Expected call to IStorageMock.GetInstallDir")
	}
}

type mIStorageMockGetInstalledModuleHash struct {
	mock               *IStorageMock
	defaultExpectation *IStorageMockGetInstalledModuleHashExpectation
	expectations       []*IStorageMockGetInstalledModuleHashExpectation

	callArgs []*IStorageMockGetInstalledModuleHashParams
	mutex    sync.RWMutex
}

// IStorageMockGetInstalledModuleHashExpectation specifies expectation struct of the IStorage.GetInstalledModuleHash
type IStorageMockGetInstalledModuleHashExpectation struct {
	mock    *IStorageMock
	params  *IStorageMockGetInstalledModuleHashParams
	results *IStorageMockGetInstalledModuleHashResults
	Counter uint64
}

// IStorageMockGetInstalledModuleHashParams contains parameters of the IStorage.GetInstalledModuleHash
type IStorageMockGetInstalledModuleHashParams struct {
	moduleName      string
	revisionVersion string
}

// IStorageMockGetInstalledModuleHashResults contains results of the IStorage.GetInstalledModuleHash
type IStorageMockGetInstalledModuleHashResults struct {
	m1  models.ModuleHash
	err error
}

// Expect sets up expected params for IStorage.GetInstalledModuleHash
func (mmGetInstalledModuleHash *mIStorageMockGetInstalledModuleHash) Expect(moduleName string, revisionVersion string) *mIStorageMockGetInstalledModuleHash {
	if mmGetInstalledModuleHash.mock.funcGetInstalledModuleHash != nil {
		mmGetInstalledModuleHash.mock.t.Fatalf("IStorageMock.GetInstalledModuleHash mock is already set by Set")
	}

	if mmGetInstalledModuleHash.defaultExpectation == nil {
		mmGetInstalledModuleHash.defaultExpectation = &IStorageMockGetInstalledModuleHashExpectation{}
	}

	mmGetInstalledModuleHash.defaultExpectation.params = &IStorageMockGetInstalledModuleHashParams{moduleName, revisionVersion}
	for _, e := range mmGetInstalledModuleHash.expectations {
		if minimock.Equal(e.params, mmGetInstalledModuleHash.defaultExpectation.params) {
			mmGetInstalledModuleHash.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetInstalledModuleHash.defaultExpectation.params)
		}
	}

	return mmGetInstalledModuleHash
}

// Inspect accepts an inspector function that has same arguments as the IStorage.GetInstalledModuleHash
func (mmGetInstalledModuleHash *mIStorageMockGetInstalledModuleHash) Inspect(f func(moduleName string, revisionVersion string)) *mIStorageMockGetInstalledModuleHash {
	if mmGetInstalledModuleHash.mock.inspectFuncGetInstalledModuleHash != nil {
		mmGetInstalledModuleHash.mock.t.Fatalf("Inspect function is already set for IStorageMock.GetInstalledModuleHash")
	}

	mmGetInstalledModuleHash.mock.inspectFuncGetInstalledModuleHash = f

	return mmGetInstalledModuleHash
}

// Return sets up results that will be returned by IStorage.GetInstalledModuleHash
func (mmGetInstalledModuleHash *mIStorageMockGetInstalledModuleHash) Return(m1 models.ModuleHash, err error) *IStorageMock {
	if mmGetInstalledModuleHash.mock.funcGetInstalledModuleHash != nil {
		mmGetInstalledModuleHash.mock.t.Fatalf("IStorageMock.GetInstalledModuleHash mock is already set by Set")
	}

	if mmGetInstalledModuleHash.defaultExpectation == nil {
		mmGetInstalledModuleHash.defaultExpectation = &IStorageMockGetInstalledModuleHashExpectation{mock: mmGetInstalledModuleHash.mock}
	}
	mmGetInstalledModuleHash.defaultExpectation.results = &IStorageMockGetInstalledModuleHashResults{m1, err}
	return mmGetInstalledModuleHash.mock
}

// Set uses given function f to mock the IStorage.GetInstalledModuleHash method
func (mmGetInstalledModuleHash *mIStorageMockGetInstalledModuleHash) Set(f func(moduleName string, revisionVersion string) (m1 models.ModuleHash, err error)) *IStorageMock {
	if mmGetInstalledModuleHash.defaultExpectation != nil {
		mmGetInstalledModuleHash.mock.t.Fatalf("Default expectation is already set for the IStorage.GetInstalledModuleHash method")
	}

	if len(mmGetInstalledModuleHash.expectations) > 0 {
		mmGetInstalledModuleHash.mock.t.Fatalf("Some expectations are already set for the IStorage.GetInstalledModuleHash method")
	}

	mmGetInstalledModuleHash.mock.funcGetInstalledModuleHash = f
	return mmGetInstalledModuleHash.mock
}

// When sets expectation for the IStorage.GetInstalledModuleHash which will trigger the result defined by the following
// Then helper
func (mmGetInstalledModuleHash *mIStorageMockGetInstalledModuleHash) When(moduleName string, revisionVersion string) *IStorageMockGetInstalledModuleHashExpectation {
	if mmGetInstalledModuleHash.mock.funcGetInstalledModuleHash != nil {
		mmGetInstalledModuleHash.mock.t.Fatalf("IStorageMock.GetInstalledModuleHash mock is already set by Set")
	}

	expectation := &IStorageMockGetInstalledModuleHashExpectation{
		mock:   mmGetInstalledModuleHash.mock,
		params: &IStorageMockGetInstalledModuleHashParams{moduleName, revisionVersion},
	}
	mmGetInstalledModuleHash.expectations = append(mmGetInstalledModuleHash.expectations, expectation)
	return expectation
}

// Then sets up IStorage.GetInstalledModuleHash return parameters for the expectation previously defined by the When method
func (e *IStorageMockGetInstalledModuleHashExpectation) Then(m1 models.ModuleHash, err error) *IStorageMock {
	e.results = &IStorageMockGetInstalledModuleHashResults{m1, err}
	return e.mock
}

// GetInstalledModuleHash implements storage.IStorage
func (mmGetInstalledModuleHash *IStorageMock) GetInstalledModuleHash(moduleName string, revisionVersion string) (m1 models.ModuleHash, err error) {
	mm_atomic.AddUint64(&mmGetInstalledModuleHash.beforeGetInstalledModuleHashCounter, 1)
	defer mm_atomic.AddUint64(&mmGetInstalledModuleHash.afterGetInstalledModuleHashCounter, 1)

	if mmGetInstalledModuleHash.inspectFuncGetInstalledModuleHash != nil {
		mmGetInstalledModuleHash.inspectFuncGetInstalledModuleHash(moduleName, revisionVersion)
	}

	mm_params := &IStorageMockGetInstalledModuleHashParams{moduleName, revisionVersion}

	// Record call args
	mmGetInstalledModuleHash.GetInstalledModuleHashMock.mutex.Lock()
	mmGetInstalledModuleHash.GetInstalledModuleHashMock.callArgs = append(mmGetInstalledModuleHash.GetInstalledModuleHashMock.callArgs, mm_params)
	mmGetInstalledModuleHash.GetInstalledModuleHashMock.mutex.Unlock()

	for _, e := range mmGetInstalledModuleHash.GetInstalledModuleHashMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmGetInstalledModuleHash.GetInstalledModuleHashMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetInstalledModuleHash.GetInstalledModuleHashMock.defaultExpectation.Counter, 1)
		mm_want := mmGetInstalledModuleHash.GetInstalledModuleHashMock.defaultExpectation.params
		mm_got := IStorageMockGetInstalledModuleHashParams{moduleName, revisionVersion}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetInstalledModuleHash.t.Errorf("IStorageMock.GetInstalledModuleHash got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetInstalledModuleHash.GetInstalledModuleHashMock.defaultExpectation.results
		if mm_results == nil {
			mmGetInstalledModuleHash.t.Fatal("No results are set for the IStorageMock.GetInstalledModuleHash")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmGetInstalledModuleHash.funcGetInstalledModuleHash != nil {
		return mmGetInstalledModuleHash.funcGetInstalledModuleHash(moduleName, revisionVersion)
	}
	mmGetInstalledModuleHash.t.Fatalf("Unexpected call to IStorageMock.GetInstalledModuleHash. %v %v", moduleName, revisionVersion)
	return
}

// GetInstalledModuleHashAfterCounter returns a count of finished IStorageMock.GetInstalledModuleHash invocations
func (mmGetInstalledModuleHash *IStorageMock) GetInstalledModuleHashAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInstalledModuleHash.afterGetInstalledModuleHashCounter)
}

// GetInstalledModuleHashBeforeCounter returns a count of IStorageMock.GetInstalledModuleHash invocations
func (mmGetInstalledModuleHash *IStorageMock) GetInstalledModuleHashBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInstalledModuleHash.beforeGetInstalledModuleHashCounter)
}

// Calls returns a list of arguments used in each call to IStorageMock.GetInstalledModuleHash.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetInstalledModuleHash *mIStorageMockGetInstalledModuleHash) Calls() []*IStorageMockGetInstalledModuleHashParams {
	mmGetInstalledModuleHash.mutex.RLock()

	argCopy := make([]*IStorageMockGetInstalledModuleHashParams, len(mmGetInstalledModuleHash.callArgs))
	copy(argCopy, mmGetInstalledModuleHash.callArgs)

	mmGetInstalledModuleHash.mutex.RUnlock()

	return argCopy
}

// MinimockGetInstalledModuleHashDone returns true if the count of the GetInstalledModuleHash invocations corresponds
// the number of defined expectations
func (m *IStorageMock) MinimockGetInstalledModuleHashDone() bool {
	for _, e := range m.GetInstalledModuleHashMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetInstalledModuleHashMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetInstalledModuleHashCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetInstalledModuleHash != nil && mm_atomic.LoadUint64(&m.afterGetInstalledModuleHashCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetInstalledModuleHashInspect logs each unmet expectation
func (m *IStorageMock) MinimockGetInstalledModuleHashInspect() {
	for _, e := range m.GetInstalledModuleHashMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IStorageMock.GetInstalledModuleHash with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetInstalledModuleHashMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetInstalledModuleHashCounter) < 1 {
		if m.GetInstalledModuleHashMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IStorageMock.GetInstalledModuleHash")
		} else {
			m.t.Errorf("Expected call to IStorageMock.GetInstalledModuleHash with params: %#v", *m.GetInstalledModuleHashMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetInstalledModuleHash != nil && mm_atomic.LoadUint64(&m.afterGetInstalledModuleHashCounter) < 1 {
		m.t.Error("Expected call to IStorageMock.GetInstalledModuleHash")
	}
}

type mIStorageMockInstall struct {
	mock               *IStorageMock
	defaultExpectation *IStorageMockInstallExpectation
	expectations       []*IStorageMockInstallExpectation

	callArgs []*IStorageMockInstallParams
	mutex    sync.RWMutex
}

// IStorageMockInstallExpectation specifies expectation struct of the IStorage.Install
type IStorageMockInstallExpectation struct {
	mock    *IStorageMock
	params  *IStorageMockInstallParams
	results *IStorageMockInstallResults
	Counter uint64
}

// IStorageMockInstallParams contains parameters of the IStorage.Install
type IStorageMockInstallParams struct {
	ctx                context.Context
	cacheDownloadPaths models.CacheDownloadPaths
	module             models.Module
	revision           models.Revision
	moduleConfig       models.ModuleConfig
}

// IStorageMockInstallResults contains results of the IStorage.Install
type IStorageMockInstallResults struct {
	m1  models.ModuleHash
	err error
}

// Expect sets up expected params for IStorage.Install
func (mmInstall *mIStorageMockInstall) Expect(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig) *mIStorageMockInstall {
	if mmInstall.mock.funcInstall != nil {
		mmInstall.mock.t.Fatalf("IStorageMock.Install mock is already set by Set")
	}

	if mmInstall.defaultExpectation == nil {
		mmInstall.defaultExpectation = &IStorageMockInstallExpectation{}
	}

	mmInstall.defaultExpectation.params = &IStorageMockInstallParams{ctx, cacheDownloadPaths, module, revision, moduleConfig}
	for _, e := range mmInstall.expectations {
		if minimock.Equal(e.params, mmInstall.defaultExpectation.params) {
			mmInstall.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInstall.defaultExpectation.params)
		}
	}

	return mmInstall
}

// Inspect accepts an inspector function that has same arguments as the IStorage.Install
func (mmInstall *mIStorageMockInstall) Inspect(f func(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig)) *mIStorageMockInstall {
	if mmInstall.mock.inspectFuncInstall != nil {
		mmInstall.mock.t.Fatalf("Inspect function is already set for IStorageMock.Install")
	}

	mmInstall.mock.inspectFuncInstall = f

	return mmInstall
}

// Return sets up results that will be returned by IStorage.Install
func (mmInstall *mIStorageMockInstall) Return(m1 models.ModuleHash, err error) *IStorageMock {
	if mmInstall.mock.funcInstall != nil {
		mmInstall.mock.t.Fatalf("IStorageMock.Install mock is already set by Set")
	}

	if mmInstall.defaultExpectation == nil {
		mmInstall.defaultExpectation = &IStorageMockInstallExpectation{mock: mmInstall.mock}
	}
	mmInstall.defaultExpectation.results = &IStorageMockInstallResults{m1, err}
	return mmInstall.mock
}

// Set uses given function f to mock the IStorage.Install method
func (mmInstall *mIStorageMockInstall) Set(f func(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig) (m1 models.ModuleHash, err error)) *IStorageMock {
	if mmInstall.defaultExpectation != nil {
		mmInstall.mock.t.Fatalf("Default expectation is already set for the IStorage.Install method")
	}

	if len(mmInstall.expectations) > 0 {
		mmInstall.mock.t.Fatalf("Some expectations are already set for the IStorage.Install method")
	}

	mmInstall.mock.funcInstall = f
	return mmInstall.mock
}

// When sets expectation for the IStorage.Install which will trigger the result defined by the following
// Then helper
func (mmInstall *mIStorageMockInstall) When(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig) *IStorageMockInstallExpectation {
	if mmInstall.mock.funcInstall != nil {
		mmInstall.mock.t.Fatalf("IStorageMock.Install mock is already set by Set")
	}

	expectation := &IStorageMockInstallExpectation{
		mock:   mmInstall.mock,
		params: &IStorageMockInstallParams{ctx, cacheDownloadPaths, module, revision, moduleConfig},
	}
	mmInstall.expectations = append(mmInstall.expectations, expectation)
	return expectation
}

// Then sets up IStorage.Install return parameters for the expectation previously defined by the When method
func (e *IStorageMockInstallExpectation) Then(m1 models.ModuleHash, err error) *IStorageMock {
	e.results = &IStorageMockInstallResults{m1, err}
	return e.mock
}

// Install implements storage.IStorage
func (mmInstall *IStorageMock) Install(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig) (m1 models.ModuleHash, err error) {
	mm_atomic.AddUint64(&mmInstall.beforeInstallCounter, 1)
	defer mm_atomic.AddUint64(&mmInstall.afterInstallCounter, 1)

	if mmInstall.inspectFuncInstall != nil {
		mmInstall.inspectFuncInstall(ctx, cacheDownloadPaths, module, revision, moduleConfig)
	}

	mm_params := &IStorageMockInstallParams{ctx, cacheDownloadPaths, module, revision, moduleConfig}

	// Record call args
	mmInstall.InstallMock.mutex.Lock()
	mmInstall.InstallMock.callArgs = append(mmInstall.InstallMock.callArgs, mm_params)
	mmInstall.InstallMock.mutex.Unlock()

	for _, e := range mmInstall.InstallMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmInstall.InstallMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInstall.InstallMock.defaultExpectation.Counter, 1)
		mm_want := mmInstall.InstallMock.defaultExpectation.params
		mm_got := IStorageMockInstallParams{ctx, cacheDownloadPaths, module, revision, moduleConfig}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInstall.t.Errorf("IStorageMock.Install got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInstall.InstallMock.defaultExpectation.results
		if mm_results == nil {
			mmInstall.t.Fatal("No results are set for the IStorageMock.Install")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmInstall.funcInstall != nil {
		return mmInstall.funcInstall(ctx, cacheDownloadPaths, module, revision, moduleConfig)
	}
	mmInstall.t.Fatalf("Unexpected call to IStorageMock.Install. %v %v %v %v %v", ctx, cacheDownloadPaths, module, revision, moduleConfig)
	return
}

// InstallAfterCounter returns a count of finished IStorageMock.Install invocations
func (mmInstall *IStorageMock) InstallAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInstall.afterInstallCounter)
}

// InstallBeforeCounter returns a count of IStorageMock.Install invocations
func (mmInstall *IStorageMock) InstallBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInstall.beforeInstallCounter)
}

// Calls returns a list of arguments used in each call to IStorageMock.Install.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInstall *mIStorageMockInstall) Calls() []*IStorageMockInstallParams {
	mmInstall.mutex.RLock()

	argCopy := make([]*IStorageMockInstallParams, len(mmInstall.callArgs))
	copy(argCopy, mmInstall.callArgs)

	mmInstall.mutex.RUnlock()

	return argCopy
}

// MinimockInstallDone returns true if the count of the Install invocations corresponds
// the number of defined expectations
func (m *IStorageMock) MinimockInstallDone() bool {
	for _, e := range m.InstallMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.InstallMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterInstallCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInstall != nil && mm_atomic.LoadUint64(&m.afterInstallCounter) < 1 {
		return false
	}
	return true
}

// MinimockInstallInspect logs each unmet expectation
func (m *IStorageMock) MinimockInstallInspect() {
	for _, e := range m.InstallMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IStorageMock.Install with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.InstallMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterInstallCounter) < 1 {
		if m.InstallMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IStorageMock.Install")
		} else {
			m.t.Errorf("Expected call to IStorageMock.Install with params: %#v", *m.InstallMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInstall != nil && mm_atomic.LoadUint64(&m.afterInstallCounter) < 1 {
		m.t.Error("Expected call to IStorageMock.Install")
	}
}

type mIStorageMockIsModuleInstalled struct {
	mock               *IStorageMock
	defaultExpectation *IStorageMockIsModuleInstalledExpectation
	expectations       []*IStorageMockIsModuleInstalledExpectation

	callArgs []*IStorageMockIsModuleInstalledParams
	mutex    sync.RWMutex
}

// IStorageMockIsModuleInstalledExpectation specifies expectation struct of the IStorage.IsModuleInstalled
type IStorageMockIsModuleInstalledExpectation struct {
	mock    *IStorageMock
	params  *IStorageMockIsModuleInstalledParams
	results *IStorageMockIsModuleInstalledResults
	Counter uint64
}

// IStorageMockIsModuleInstalledParams contains parameters of the IStorage.IsModuleInstalled
type IStorageMockIsModuleInstalledParams struct {
	module models.Module
}

// IStorageMockIsModuleInstalledResults contains results of the IStorage.IsModuleInstalled
type IStorageMockIsModuleInstalledResults struct {
	b1  bool
	err error
}

// Expect sets up expected params for IStorage.IsModuleInstalled
func (mmIsModuleInstalled *mIStorageMockIsModuleInstalled) Expect(module models.Module) *mIStorageMockIsModuleInstalled {
	if mmIsModuleInstalled.mock.funcIsModuleInstalled != nil {
		mmIsModuleInstalled.mock.t.Fatalf("IStorageMock.IsModuleInstalled mock is already set by Set")
	}

	if mmIsModuleInstalled.defaultExpectation == nil {
		mmIsModuleInstalled.defaultExpectation = &IStorageMockIsModuleInstalledExpectation{}
	}

	mmIsModuleInstalled.defaultExpectation.params = &IStorageMockIsModuleInstalledParams{module}
	for _, e := range mmIsModuleInstalled.expectations {
		if minimock.Equal(e.params, mmIsModuleInstalled.defaultExpectation.params) {
			mmIsModuleInstalled.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmIsModuleInstalled.defaultExpectation.params)
		}
	}

	return mmIsModuleInstalled
}

// Inspect accepts an inspector function that has same arguments as the IStorage.IsModuleInstalled
func (mmIsModuleInstalled *mIStorageMockIsModuleInstalled) Inspect(f func(module models.Module)) *mIStorageMockIsModuleInstalled {
	if mmIsModuleInstalled.mock.inspectFuncIsModuleInstalled != nil {
		mmIsModuleInstalled.mock.t.Fatalf("Inspect function is already set for IStorageMock.IsModuleInstalled")
	}

	mmIsModuleInstalled.mock.inspectFuncIsModuleInstalled = f

	return mmIsModuleInstalled
}

// Return sets up results that will be returned by IStorage.IsModuleInstalled
func (mmIsModuleInstalled *mIStorageMockIsModuleInstalled) Return(b1 bool, err error) *IStorageMock {
	if mmIsModuleInstalled.mock.funcIsModuleInstalled != nil {
		mmIsModuleInstalled.mock.t.Fatalf("IStorageMock.IsModuleInstalled mock is already set by Set")
	}

	if mmIsModuleInstalled.defaultExpectation == nil {
		mmIsModuleInstalled.defaultExpectation = &IStorageMockIsModuleInstalledExpectation{mock: mmIsModuleInstalled.mock}
	}
	mmIsModuleInstalled.defaultExpectation.results = &IStorageMockIsModuleInstalledResults{b1, err}
	return mmIsModuleInstalled.mock
}

// Set uses given function f to mock the IStorage.IsModuleInstalled method
func (mmIsModuleInstalled *mIStorageMockIsModuleInstalled) Set(f func(module models.Module) (b1 bool, err error)) *IStorageMock {
	if mmIsModuleInstalled.defaultExpectation != nil {
		mmIsModuleInstalled.mock.t.Fatalf("Default expectation is already set for the IStorage.IsModuleInstalled method")
	}

	if len(mmIsModuleInstalled.expectations) > 0 {
		mmIsModuleInstalled.mock.t.Fatalf("Some expectations are already set for the IStorage.IsModuleInstalled method")
	}

	mmIsModuleInstalled.mock.funcIsModuleInstalled = f
	return mmIsModuleInstalled.mock
}

// When sets expectation for the IStorage.IsModuleInstalled which will trigger the result defined by the following
// Then helper
func (mmIsModuleInstalled *mIStorageMockIsModuleInstalled) When(module models.Module) *IStorageMockIsModuleInstalledExpectation {
	if mmIsModuleInstalled.mock.funcIsModuleInstalled != nil {
		mmIsModuleInstalled.mock.t.Fatalf("IStorageMock.IsModuleInstalled mock is already set by Set")
	}

	expectation := &IStorageMockIsModuleInstalledExpectation{
		mock:   mmIsModuleInstalled.mock,
		params: &IStorageMockIsModuleInstalledParams{module},
	}
	mmIsModuleInstalled.expectations = append(mmIsModuleInstalled.expectations, expectation)
	return expectation
}

// Then sets up IStorage.IsModuleInstalled return parameters for the expectation previously defined by the When method
func (e *IStorageMockIsModuleInstalledExpectation) Then(b1 bool, err error) *IStorageMock {
	e.results = &IStorageMockIsModuleInstalledResults{b1, err}
	return e.mock
}

// IsModuleInstalled implements storage.IStorage
func (mmIsModuleInstalled *IStorageMock) IsModuleInstalled(module models.Module) (b1 bool, err error) {
	mm_atomic.AddUint64(&mmIsModuleInstalled.beforeIsModuleInstalledCounter, 1)
	defer mm_atomic.AddUint64(&mmIsModuleInstalled.afterIsModuleInstalledCounter, 1)

	if mmIsModuleInstalled.inspectFuncIsModuleInstalled != nil {
		mmIsModuleInstalled.inspectFuncIsModuleInstalled(module)
	}

	mm_params := &IStorageMockIsModuleInstalledParams{module}

	// Record call args
	mmIsModuleInstalled.IsModuleInstalledMock.mutex.Lock()
	mmIsModuleInstalled.IsModuleInstalledMock.callArgs = append(mmIsModuleInstalled.IsModuleInstalledMock.callArgs, mm_params)
	mmIsModuleInstalled.IsModuleInstalledMock.mutex.Unlock()

	for _, e := range mmIsModuleInstalled.IsModuleInstalledMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmIsModuleInstalled.IsModuleInstalledMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIsModuleInstalled.IsModuleInstalledMock.defaultExpectation.Counter, 1)
		mm_want := mmIsModuleInstalled.IsModuleInstalledMock.defaultExpectation.params
		mm_got := IStorageMockIsModuleInstalledParams{module}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmIsModuleInstalled.t.Errorf("IStorageMock.IsModuleInstalled got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmIsModuleInstalled.IsModuleInstalledMock.defaultExpectation.results
		if mm_results == nil {
			mmIsModuleInstalled.t.Fatal("No results are set for the IStorageMock.IsModuleInstalled")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmIsModuleInstalled.funcIsModuleInstalled != nil {
		return mmIsModuleInstalled.funcIsModuleInstalled(module)
	}
	mmIsModuleInstalled.t.Fatalf("Unexpected call to IStorageMock.IsModuleInstalled. %v", module)
	return
}

// IsModuleInstalledAfterCounter returns a count of finished IStorageMock.IsModuleInstalled invocations
func (mmIsModuleInstalled *IStorageMock) IsModuleInstalledAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsModuleInstalled.afterIsModuleInstalledCounter)
}

// IsModuleInstalledBeforeCounter returns a count of IStorageMock.IsModuleInstalled invocations
func (mmIsModuleInstalled *IStorageMock) IsModuleInstalledBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsModuleInstalled.beforeIsModuleInstalledCounter)
}

// Calls returns a list of arguments used in each call to IStorageMock.IsModuleInstalled.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmIsModuleInstalled *mIStorageMockIsModuleInstalled) Calls() []*IStorageMockIsModuleInstalledParams {
	mmIsModuleInstalled.mutex.RLock()

	argCopy := make([]*IStorageMockIsModuleInstalledParams, len(mmIsModuleInstalled.callArgs))
	copy(argCopy, mmIsModuleInstalled.callArgs)

	mmIsModuleInstalled.mutex.RUnlock()

	return argCopy
}

// MinimockIsModuleInstalledDone returns true if the count of the IsModuleInstalled invocations corresponds
// the number of defined expectations
func (m *IStorageMock) MinimockIsModuleInstalledDone() bool {
	for _, e := range m.IsModuleInstalledMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.IsModuleInstalledMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterIsModuleInstalledCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIsModuleInstalled != nil && mm_atomic.LoadUint64(&m.afterIsModuleInstalledCounter) < 1 {
		return false
	}
	return true
}

// MinimockIsModuleInstalledInspect logs each unmet expectation
func (m *IStorageMock) MinimockIsModuleInstalledInspect() {
	for _, e := range m.IsModuleInstalledMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IStorageMock.IsModuleInstalled with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.IsModuleInstalledMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterIsModuleInstalledCounter) < 1 {
		if m.IsModuleInstalledMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IStorageMock.IsModuleInstalled")
		} else {
			m.t.Errorf("Expected call to IStorageMock.IsModuleInstalled with params: %#v", *m.IsModuleInstalledMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIsModuleInstalled != nil && mm_atomic.LoadUint64(&m.afterIsModuleInstalledCounter) < 1 {
		m.t.Error("Expected call to IStorageMock.IsModuleInstalled")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IStorageMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockCreateCacheDownloadDirInspect()

		m.MinimockCreateCacheRepositoryDirInspect()

		m.MinimockGetCacheDownloadPathsInspect()

		m.MinimockGetInstallDirInspect()

		m.MinimockGetInstalledModuleHashInspect()

		m.MinimockInstallInspect()

		m.MinimockIsModuleInstalledInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateCacheDownloadDirDone() &&
		m.MinimockCreateCacheRepositoryDirDone() &&
		m.MinimockGetCacheDownloadPathsDone() &&
		m.MinimockGetInstallDirDone() &&
		m.MinimockGetInstalledModuleHashDone() &&
		m.MinimockInstallDone() &&
		m.MinimockIsModuleInstalledDone()
}
