package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// IWalkerMock implements generate.IWalker
type IWalkerMock struct {
	t minimock.Tester

	funcWalkDir          func(root string, path string, callback func(path string, err error) error) (err error)
	inspectFuncWalkDir   func(root string, path string, callback func(path string, err error) error)
	afterWalkDirCounter  uint64
	beforeWalkDirCounter uint64
	WalkDirMock          mIWalkerMockWalkDir
}

// NewIWalkerMock returns a mock for generate.IWalker
func NewIWalkerMock(t minimock.Tester) *IWalkerMock {
	m := &IWalkerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.WalkDirMock = mIWalkerMockWalkDir{mock: m}
	m.WalkDirMock.callArgs = []*IWalkerMockWalkDirParams{}

	return m
}

type mIWalkerMockWalkDir struct {
	mock               *IWalkerMock
	defaultExpectation *IWalkerMockWalkDirExpectation
	expectations       []*IWalkerMockWalkDirExpectation

	callArgs []*IWalkerMockWalkDirParams
	mutex    sync.RWMutex
}

// IWalkerMockWalkDirExpectation specifies expectation struct of the IWalker.WalkDir
type IWalkerMockWalkDirExpectation struct {
	mock    *IWalkerMock
	params  *IWalkerMockWalkDirParams
	results *IWalkerMockWalkDirResults
	Counter uint64
}

// IWalkerMockWalkDirParams contains parameters of the IWalker.WalkDir
type IWalkerMockWalkDirParams struct {
	root     string
	path     string
	callback func(path string, err error) error
}

// IWalkerMockWalkDirResults contains results of the IWalker.WalkDir
type IWalkerMockWalkDirResults struct {
	err error
}

// Expect sets up expected params for IWalker.WalkDir
func (mmWalkDir *mIWalkerMockWalkDir) Expect(root string, path string, callback func(path string, err error) error) *mIWalkerMockWalkDir {
	if mmWalkDir.mock.funcWalkDir != nil {
		mmWalkDir.mock.t.Fatalf("IWalkerMock.WalkDir mock is already set by Set")
	}

	if mmWalkDir.defaultExpectation == nil {
		mmWalkDir.defaultExpectation = &IWalkerMockWalkDirExpectation{}
	}

	mmWalkDir.defaultExpectation.params = &IWalkerMockWalkDirParams{root, path, callback}
	for _, e := range mmWalkDir.expectations {
		if minimock.Equal(e.params, mmWalkDir.defaultExpectation.params) {
			mmWalkDir.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWalkDir.defaultExpectation.params)
		}
	}

	return mmWalkDir
}

// Inspect accepts an inspector function that has same arguments as the IWalker.WalkDir
func (mmWalkDir *mIWalkerMockWalkDir) Inspect(f func(root string, path string, callback func(path string, err error) error)) *mIWalkerMockWalkDir {
	if mmWalkDir.mock.inspectFuncWalkDir != nil {
		mmWalkDir.mock.t.Fatalf("Inspect function is already set for IWalkerMock.WalkDir")
	}

	mmWalkDir.mock.inspectFuncWalkDir = f

	return mmWalkDir
}

// Return sets up results that will be returned by IWalker.WalkDir
func (mmWalkDir *mIWalkerMockWalkDir) Return(err error) *IWalkerMock {
	if mmWalkDir.mock.funcWalkDir != nil {
		mmWalkDir.mock.t.Fatalf("IWalkerMock.WalkDir mock is already set by Set")
	}

	if mmWalkDir.defaultExpectation == nil {
		mmWalkDir.defaultExpectation = &IWalkerMockWalkDirExpectation{mock: mmWalkDir.mock}
	}
	mmWalkDir.defaultExpectation.results = &IWalkerMockWalkDirResults{err}
	return mmWalkDir.mock
}

// Set uses given function f to mock the IWalker.WalkDir method
func (mmWalkDir *mIWalkerMockWalkDir) Set(f func(root string, path string, callback func(path string, err error) error) (err error)) *IWalkerMock {
	if mmWalkDir.defaultExpectation != nil {
		mmWalkDir.mock.t.Fatalf("Default expectation is already set for the IWalker.WalkDir method")
	}

	if len(mmWalkDir.expectations) > 0 {
		mmWalkDir.mock.t.Fatalf("Some expectations are already set for the IWalker.WalkDir method")
	}

	mmWalkDir.mock.funcWalkDir = f
	return mmWalkDir.mock
}

// When sets expectation for the IWalker.WalkDir which will trigger the result defined by the following
// Then helper
func (mmWalkDir *mIWalkerMockWalkDir) When(root string, path string, callback func(path string, err error) error) *IWalkerMockWalkDirExpectation {
	if mmWalkDir.mock.funcWalkDir != nil {
		mmWalkDir.mock.t.Fatalf("IWalkerMock.WalkDir mock is already set by Set")
	}

	expectation := &IWalkerMockWalkDirExpectation{
		mock:   mmWalkDir.mock,
		params: &IWalkerMockWalkDirParams{root, path, callback},
	}
	mmWalkDir.expectations = append(mmWalkDir.expectations, expectation)
	return expectation
}

// Then sets up IWalker.WalkDir return parameters for the expectation previously defined by the When method
func (e *IWalkerMockWalkDirExpectation) Then(err error) *IWalkerMock {
	e.results = &IWalkerMockWalkDirResults{err}
	return e.mock
}

// WalkDir implements generate.IWalker
func (mmWalkDir *IWalkerMock) WalkDir(root string, path string, callback func(path string, err error) error) (err error) {
	mm_atomic.AddUint64(&mmWalkDir.beforeWalkDirCounter, 1)
	defer mm_atomic.AddUint64(&mmWalkDir.afterWalkDirCounter, 1)

	if mmWalkDir.inspectFuncWalkDir != nil {
		mmWalkDir.inspectFuncWalkDir(root, path, callback)
	}

	mm_params := &IWalkerMockWalkDirParams{root, path, callback}

	// Record call args
	mmWalkDir.WalkDirMock.mutex.Lock()
	mmWalkDir.WalkDirMock.callArgs = append(mmWalkDir.WalkDirMock.callArgs, mm_params)
	mmWalkDir.WalkDirMock.mutex.Unlock()

	for _, e := range mmWalkDir.WalkDirMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmWalkDir.WalkDirMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWalkDir.WalkDirMock.defaultExpectation.Counter, 1)
		mm_want := mmWalkDir.WalkDirMock.defaultExpectation.params
		mm_got := IWalkerMockWalkDirParams{root, path, callback}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWalkDir.t.Errorf("IWalkerMock.WalkDir got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWalkDir.WalkDirMock.defaultExpectation.results
		if mm_results == nil {
			mmWalkDir.t.Fatal("No results are set for the IWalkerMock.WalkDir")
		}
		return (*mm_results).err
	}
	if mmWalkDir.funcWalkDir != nil {
		return mmWalkDir.funcWalkDir(root, path, callback)
	}
	mmWalkDir.t.Fatalf("Unexpected call to IWalkerMock.WalkDir. %v %v %v", root, path, callback)
	return
}

// WalkDirAfterCounter returns a count of finished IWalkerMock.WalkDir invocations
func (mmWalkDir *IWalkerMock) WalkDirAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWalkDir.afterWalkDirCounter)
}

// WalkDirBeforeCounter returns a count of IWalkerMock.WalkDir invocations
func (mmWalkDir *IWalkerMock) WalkDirBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWalkDir.beforeWalkDirCounter)
}

// Calls returns a list of arguments used in each call to IWalkerMock.WalkDir.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWalkDir *mIWalkerMockWalkDir) Calls() []*IWalkerMockWalkDirParams {
	mmWalkDir.mutex.RLock()

	argCopy := make([]*IWalkerMockWalkDirParams, len(mmWalkDir.callArgs))
	copy(argCopy, mmWalkDir.callArgs)

	mmWalkDir.mutex.RUnlock()

	return argCopy
}

// MinimockWalkDirDone returns true if the count of the WalkDir invocations corresponds
// the number of defined expectations
func (m *IWalkerMock) MinimockWalkDirDone() bool {
	for _, e := range m.WalkDirMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.WalkDirMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterWalkDirCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWalkDir != nil && mm_atomic.LoadUint64(&m.afterWalkDirCounter) < 1 {
		return false
	}
	return true
}

// MinimockWalkDirInspect logs each unmet expectation
func (m *IWalkerMock) MinimockWalkDirInspect() {
	for _, e := range m.WalkDirMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IWalkerMock.WalkDir with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.WalkDirMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterWalkDirCounter) < 1 {
		if m.WalkDirMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IWalkerMock.WalkDir")
		} else {
			m.t.Errorf("Expected call to IWalkerMock.WalkDir with params: %#v", *m.WalkDirMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWalkDir != nil && mm_atomic.LoadUint64(&m.afterWalkDirCounter) < 1 {
		m.t.Error("Expected call to IWalkerMock.WalkDir")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IWalkerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockWalkDirInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IWalkerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IWalkerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockWalkDirDone()
}
