package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"go.redsock.ru/moti/internal/models"
)

// RepoMock implements repository.Repo
type RepoMock struct {
	t minimock.Tester

	funcArchive          func(ctx context.Context, revision models.Revision, cacheDownloadPaths models.CacheDownloadPaths) (err error)
	inspectFuncArchive   func(ctx context.Context, revision models.Revision, cacheDownloadPaths models.CacheDownloadPaths)
	afterArchiveCounter  uint64
	beforeArchiveCounter uint64
	ArchiveMock          mRepoMockArchive

	funcFetch          func(ctx context.Context, revision models.Revision) (err error)
	inspectFuncFetch   func(ctx context.Context, revision models.Revision)
	afterFetchCounter  uint64
	beforeFetchCounter uint64
	FetchMock          mRepoMockFetch

	funcGetFiles          func(ctx context.Context, revision models.Revision, dirs ...string) (sa1 []string, err error)
	inspectFuncGetFiles   func(ctx context.Context, revision models.Revision, dirs ...string)
	afterGetFilesCounter  uint64
	beforeGetFilesCounter uint64
	GetFilesMock          mRepoMockGetFiles

	funcReadFile          func(ctx context.Context, revision models.Revision, fileName string) (s1 string, err error)
	inspectFuncReadFile   func(ctx context.Context, revision models.Revision, fileName string)
	afterReadFileCounter  uint64
	beforeReadFileCounter uint64
	ReadFileMock          mRepoMockReadFile

	funcReadRevision          func(ctx context.Context, requestedVersion models.RequestedVersion) (r1 models.Revision, err error)
	inspectFuncReadRevision   func(ctx context.Context, requestedVersion models.RequestedVersion)
	afterReadRevisionCounter  uint64
	beforeReadRevisionCounter uint64
	ReadRevisionMock          mRepoMockReadRevision
}

// NewRepoMock returns a mock for repository.Repo
func NewRepoMock(t minimock.Tester) *RepoMock {
	m := &RepoMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ArchiveMock = mRepoMockArchive{mock: m}
	m.ArchiveMock.callArgs = []*RepoMockArchiveParams{}

	m.FetchMock = mRepoMockFetch{mock: m}
	m.FetchMock.callArgs = []*RepoMockFetchParams{}

	m.GetFilesMock = mRepoMockGetFiles{mock: m}
	m.GetFilesMock.callArgs = []*RepoMockGetFilesParams{}

	m.ReadFileMock = mRepoMockReadFile{mock: m}
	m.ReadFileMock.callArgs = []*RepoMockReadFileParams{}

	m.ReadRevisionMock = mRepoMockReadRevision{mock: m}
	m.ReadRevisionMock.callArgs = []*RepoMockReadRevisionParams{}

	return m
}

type mRepoMockArchive struct {
	mock               *RepoMock
	defaultExpectation *RepoMockArchiveExpectation
	expectations       []*RepoMockArchiveExpectation

	callArgs []*RepoMockArchiveParams
	mutex    sync.RWMutex
}

// RepoMockArchiveExpectation specifies expectation struct of the Repo.Archive
type RepoMockArchiveExpectation struct {
	mock    *RepoMock
	params  *RepoMockArchiveParams
	results *RepoMockArchiveResults
	Counter uint64
}

// RepoMockArchiveParams contains parameters of the Repo.Archive
type RepoMockArchiveParams struct {
	ctx                context.Context
	revision           models.Revision
	cacheDownloadPaths models.CacheDownloadPaths
}

// RepoMockArchiveResults contains results of the Repo.Archive
type RepoMockArchiveResults struct {
	err error
}

// Expect sets up expected params for Repo.Archive
func (mmArchive *mRepoMockArchive) Expect(ctx context.Context, revision models.Revision, cacheDownloadPaths models.CacheDownloadPaths) *mRepoMockArchive {
	if mmArchive.mock.funcArchive != nil {
		mmArchive.mock.t.Fatalf("RepoMock.Archive mock is already set by Set")
	}

	if mmArchive.defaultExpectation == nil {
		mmArchive.defaultExpectation = &RepoMockArchiveExpectation{}
	}

	mmArchive.defaultExpectation.params = &RepoMockArchiveParams{ctx, revision, cacheDownloadPaths}
	for _, e := range mmArchive.expectations {
		if minimock.Equal(e.params, mmArchive.defaultExpectation.params) {
			mmArchive.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmArchive.defaultExpectation.params)
		}
	}

	return mmArchive
}

// Inspect accepts an inspector function that has same arguments as the Repo.Archive
func (mmArchive *mRepoMockArchive) Inspect(f func(ctx context.Context, revision models.Revision, cacheDownloadPaths models.CacheDownloadPaths)) *mRepoMockArchive {
	if mmArchive.mock.inspectFuncArchive != nil {
		mmArchive.mock.t.Fatalf("Inspect function is already set for RepoMock.Archive")
	}

	mmArchive.mock.inspectFuncArchive = f

	return mmArchive
}

// Return sets up results that will be returned by Repo.Archive
func (mmArchive *mRepoMockArchive) Return(err error) *RepoMock {
	if mmArchive.mock.funcArchive != nil {
		mmArchive.mock.t.Fatalf("RepoMock.Archive mock is already set by Set")
	}

	if mmArchive.defaultExpectation == nil {
		mmArchive.defaultExpectation = &RepoMockArchiveExpectation{mock: mmArchive.mock}
	}
	mmArchive.defaultExpectation.results = &RepoMockArchiveResults{err}
	return mmArchive.mock
}

// Set uses given function f to mock the Repo.Archive method
func (mmArchive *mRepoMockArchive) Set(f func(ctx context.Context, revision models.Revision, cacheDownloadPaths models.CacheDownloadPaths) (err error)) *RepoMock {
	if mmArchive.defaultExpectation != nil {
		mmArchive.mock.t.Fatalf("Default expectation is already set for the Repo.Archive method")
	}

	if len(mmArchive.expectations) > 0 {
		mmArchive.mock.t.Fatalf("Some expectations are already set for the Repo.Archive method")
	}

	mmArchive.mock.funcArchive = f
	return mmArchive.mock
}

// When sets expectation for the Repo.Archive which will trigger the result defined by the following
// Then helper
func (mmArchive *mRepoMockArchive) When(ctx context.Context, revision models.Revision, cacheDownloadPaths models.CacheDownloadPaths) *RepoMockArchiveExpectation {
	if mmArchive.mock.funcArchive != nil {
		mmArchive.mock.t.Fatalf("RepoMock.Archive mock is already set by Set")
	}

	expectation := &RepoMockArchiveExpectation{
		mock:   mmArchive.mock,
		params: &RepoMockArchiveParams{ctx, revision, cacheDownloadPaths},
	}
	mmArchive.expectations = append(mmArchive.expectations, expectation)
	return expectation
}

// Then sets up Repo.Archive return parameters for the expectation previously defined by the When method
func (e *RepoMockArchiveExpectation) Then(err error) *RepoMock {
	e.results = &RepoMockArchiveResults{err}
	return e.mock
}

// Archive implements repository.Repo
func (mmArchive *RepoMock) Archive(ctx context.Context, revision models.Revision, cacheDownloadPaths models.CacheDownloadPaths) (err error) {
	mm_atomic.AddUint64(&mmArchive.beforeArchiveCounter, 1)
	defer mm_atomic.AddUint64(&mmArchive.afterArchiveCounter, 1)

	if mmArchive.inspectFuncArchive != nil {
		mmArchive.inspectFuncArchive(ctx, revision, cacheDownloadPaths)
	}

	mm_params := &RepoMockArchiveParams{ctx, revision, cacheDownloadPaths}

	// Record call args
	mmArchive.ArchiveMock.mutex.Lock()
	mmArchive.ArchiveMock.callArgs = append(mmArchive.ArchiveMock.callArgs, mm_params)
	mmArchive.ArchiveMock.mutex.Unlock()

	for _, e := range mmArchive.ArchiveMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmArchive.ArchiveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmArchive.ArchiveMock.defaultExpectation.Counter, 1)
		mm_want := mmArchive.ArchiveMock.defaultExpectation.params
		mm_got := RepoMockArchiveParams{ctx, revision, cacheDownloadPaths}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmArchive.t.Errorf("RepoMock.Archive got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmArchive.ArchiveMock.defaultExpectation.results
		if mm_results == nil {
			mmArchive.t.Fatal("No results are set for the RepoMock.Archive")
		}
		return (*mm_results).err
	}
	if mmArchive.funcArchive != nil {
		return mmArchive.funcArchive(ctx, revision, cacheDownloadPaths)
	}
	mmArchive.t.Fatalf("Unexpected call to RepoMock.Archive. %v %v %v", ctx, revision, cacheDownloadPaths)
	return
}

// ArchiveAfterCounter returns a count of finished RepoMock.Archive invocations
func (mmArchive *RepoMock) ArchiveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmArchive.afterArchiveCounter)
}

// ArchiveBeforeCounter returns a count of RepoMock.Archive invocations
func (mmArchive *RepoMock) ArchiveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmArchive.beforeArchiveCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.Archive.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmArchive *mRepoMockArchive) Calls() []*RepoMockArchiveParams {
	mmArchive.mutex.RLock()

	argCopy := make([]*RepoMockArchiveParams, len(mmArchive.callArgs))
	copy(argCopy, mmArchive.callArgs)

	mmArchive.mutex.RUnlock()

	return argCopy
}

// MinimockArchiveDone returns true if the count of the Archive invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockArchiveDone() bool {
	for _, e := range m.ArchiveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ArchiveMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterArchiveCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcArchive != nil && mm_atomic.LoadUint64(&m.afterArchiveCounter) < 1 {
		return false
	}
	return true
}

// MinimockArchiveInspect logs each unmet expectation
func (m *RepoMock) MinimockArchiveInspect() {
	for _, e := range m.ArchiveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.Archive with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ArchiveMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterArchiveCounter) < 1 {
		if m.ArchiveMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepoMock.Archive")
		} else {
			m.t.Errorf("Expected call to RepoMock.Archive with params: %#v", *m.ArchiveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcArchive != nil && mm_atomic.LoadUint64(&m.afterArchiveCounter) < 1 {
		m.t.Error("Expected call to RepoMock.Archive")
	}
}

type mRepoMockFetch struct {
	mock               *RepoMock
	defaultExpectation *RepoMockFetchExpectation
	expectations       []*RepoMockFetchExpectation

	callArgs []*RepoMockFetchParams
	mutex    sync.RWMutex
}

// RepoMockFetchExpectation specifies expectation struct of the Repo.Fetch
type RepoMockFetchExpectation struct {
	mock    *RepoMock
	params  *RepoMockFetchParams
	results *RepoMockFetchResults
	Counter uint64
}

// RepoMockFetchParams contains parameters of the Repo.Fetch
type RepoMockFetchParams struct {
	ctx      context.Context
	revision models.Revision
}

// RepoMockFetchResults contains results of the Repo.Fetch
type RepoMockFetchResults struct {
	err error
}

// Expect sets up expected params for Repo.Fetch
func (mmFetch *mRepoMockFetch) Expect(ctx context.Context, revision models.Revision) *mRepoMockFetch {
	if mmFetch.mock.funcFetch != nil {
		mmFetch.mock.t.Fatalf("RepoMock.Fetch mock is already set by Set")
	}

	if mmFetch.defaultExpectation == nil {
		mmFetch.defaultExpectation = &RepoMockFetchExpectation{}
	}

	mmFetch.defaultExpectation.params = &RepoMockFetchParams{ctx, revision}
	for _, e := range mmFetch.expectations {
		if minimock.Equal(e.params, mmFetch.defaultExpectation.params) {
			mmFetch.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFetch.defaultExpectation.params)
		}
	}

	return mmFetch
}

// Inspect accepts an inspector function that has same arguments as the Repo.Fetch
func (mmFetch *mRepoMockFetch) Inspect(f func(ctx context.Context, revision models.Revision)) *mRepoMockFetch {
	if mmFetch.mock.inspectFuncFetch != nil {
		mmFetch.mock.t.Fatalf("Inspect function is already set for RepoMock.Fetch")
	}

	mmFetch.mock.inspectFuncFetch = f

	return mmFetch
}

// Return sets up results that will be returned by Repo.Fetch
func (mmFetch *mRepoMockFetch) Return(err error) *RepoMock {
	if mmFetch.mock.funcFetch != nil {
		mmFetch.mock.t.Fatalf("RepoMock.Fetch mock is already set by Set")
	}

	if mmFetch.defaultExpectation == nil {
		mmFetch.defaultExpectation = &RepoMockFetchExpectation{mock: mmFetch.mock}
	}
	mmFetch.defaultExpectation.results = &RepoMockFetchResults{err}
	return mmFetch.mock
}

// Set uses given function f to mock the Repo.Fetch method
func (mmFetch *mRepoMockFetch) Set(f func(ctx context.Context, revision models.Revision) (err error)) *RepoMock {
	if mmFetch.defaultExpectation != nil {
		mmFetch.mock.t.Fatalf("Default expectation is already set for the Repo.Fetch method")
	}

	if len(mmFetch.expectations) > 0 {
		mmFetch.mock.t.Fatalf("Some expectations are already set for the Repo.Fetch method")
	}

	mmFetch.mock.funcFetch = f
	return mmFetch.mock
}

// When sets expectation for the Repo.Fetch which will trigger the result defined by the following
// Then helper
func (mmFetch *mRepoMockFetch) When(ctx context.Context, revision models.Revision) *RepoMockFetchExpectation {
	if mmFetch.mock.funcFetch != nil {
		mmFetch.mock.t.Fatalf("RepoMock.Fetch mock is already set by Set")
	}

	expectation := &RepoMockFetchExpectation{
		mock:   mmFetch.mock,
		params: &RepoMockFetchParams{ctx, revision},
	}
	mmFetch.expectations = append(mmFetch.expectations, expectation)
	return expectation
}

// Then sets up Repo.Fetch return parameters for the expectation previously defined by the When method
func (e *RepoMockFetchExpectation) Then(err error) *RepoMock {
	e.results = &RepoMockFetchResults{err}
	return e.mock
}

// Fetch implements repository.Repo
func (mmFetch *RepoMock) Fetch(ctx context.Context, revision models.Revision) (err error) {
	mm_atomic.AddUint64(&mmFetch.beforeFetchCounter, 1)
	defer mm_atomic.AddUint64(&mmFetch.afterFetchCounter, 1)

	if mmFetch.inspectFuncFetch != nil {
		mmFetch.inspectFuncFetch(ctx, revision)
	}

	mm_params := &RepoMockFetchParams{ctx, revision}

	// Record call args
	mmFetch.FetchMock.mutex.Lock()
	mmFetch.FetchMock.callArgs = append(mmFetch.FetchMock.callArgs, mm_params)
	mmFetch.FetchMock.mutex.Unlock()

	for _, e := range mmFetch.FetchMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmFetch.FetchMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFetch.FetchMock.defaultExpectation.Counter, 1)
		mm_want := mmFetch.FetchMock.defaultExpectation.params
		mm_got := RepoMockFetchParams{ctx, revision}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFetch.t.Errorf("RepoMock.Fetch got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFetch.FetchMock.defaultExpectation.results
		if mm_results == nil {
			mmFetch.t.Fatal("No results are set for the RepoMock.Fetch")
		}
		return (*mm_results).err
	}
	if mmFetch.funcFetch != nil {
		return mmFetch.funcFetch(ctx, revision)
	}
	mmFetch.t.Fatalf("Unexpected call to RepoMock.Fetch. %v %v", ctx, revision)
	return
}

// FetchAfterCounter returns a count of finished RepoMock.Fetch invocations
func (mmFetch *RepoMock) FetchAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetch.afterFetchCounter)
}

// FetchBeforeCounter returns a count of RepoMock.Fetch invocations
func (mmFetch *RepoMock) FetchBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetch.beforeFetchCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.Fetch.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFetch *mRepoMockFetch) Calls() []*RepoMockFetchParams {
	mmFetch.mutex.RLock()

	argCopy := make([]*RepoMockFetchParams, len(mmFetch.callArgs))
	copy(argCopy, mmFetch.callArgs)

	mmFetch.mutex.RUnlock()

	return argCopy
}

// MinimockFetchDone returns true if the count of the Fetch invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockFetchDone() bool {
	for _, e := range m.FetchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.FetchMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterFetchCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFetch != nil && mm_atomic.LoadUint64(&m.afterFetchCounter) < 1 {
		return false
	}
	return true
}

// MinimockFetchInspect logs each unmet expectation
func (m *RepoMock) MinimockFetchInspect() {
	for _, e := range m.FetchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.Fetch with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.FetchMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterFetchCounter) < 1 {
		if m.FetchMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepoMock.Fetch")
		} else {
			m.t.Errorf("Expected call to RepoMock.Fetch with params: %#v", *m.FetchMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFetch != nil && mm_atomic.LoadUint64(&m.afterFetchCounter) < 1 {
		m.t.Error("Expected call to RepoMock.Fetch")
	}
}

type mRepoMockGetFiles struct {
	mock               *RepoMock
	defaultExpectation *RepoMockGetFilesExpectation
	expectations       []*RepoMockGetFilesExpectation

	callArgs []*RepoMockGetFilesParams
	mutex    sync.RWMutex
}

// RepoMockGetFilesExpectation specifies expectation struct of the Repo.GetFiles
type RepoMockGetFilesExpectation struct {
	mock    *RepoMock
	params  *RepoMockGetFilesParams
	results *RepoMockGetFilesResults
	Counter uint64
}

// RepoMockGetFilesParams contains parameters of the Repo.GetFiles
type RepoMockGetFilesParams struct {
	ctx      context.Context
	revision models.Revision
	dirs     []string
}

// RepoMockGetFilesResults contains results of the Repo.GetFiles
type RepoMockGetFilesResults struct {
	sa1 []string
	err error
}

// Expect sets up expected params for Repo.GetFiles
func (mmGetFiles *mRepoMockGetFiles) Expect(ctx context.Context, revision models.Revision, dirs ...string) *mRepoMockGetFiles {
	if mmGetFiles.mock.funcGetFiles != nil {
		mmGetFiles.mock.t.Fatalf("RepoMock.GetFiles mock is already set by Set")
	}

	if mmGetFiles.defaultExpectation == nil {
		mmGetFiles.defaultExpectation = &RepoMockGetFilesExpectation{}
	}

	mmGetFiles.defaultExpectation.params = &RepoMockGetFilesParams{ctx, revision, dirs}
	for _, e := range mmGetFiles.expectations {
		if minimock.Equal(e.params, mmGetFiles.defaultExpectation.params) {
			mmGetFiles.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetFiles.defaultExpectation.params)
		}
	}

	return mmGetFiles
}

// Inspect accepts an inspector function that has same arguments as the Repo.GetFiles
func (mmGetFiles *mRepoMockGetFiles) Inspect(f func(ctx context.Context, revision models.Revision, dirs ...string)) *mRepoMockGetFiles {
	if mmGetFiles.mock.inspectFuncGetFiles != nil {
		mmGetFiles.mock.t.Fatalf("Inspect function is already set for RepoMock.GetFiles")
	}

	mmGetFiles.mock.inspectFuncGetFiles = f

	return mmGetFiles
}

// Return sets up results that will be returned by Repo.GetFiles
func (mmGetFiles *mRepoMockGetFiles) Return(sa1 []string, err error) *RepoMock {
	if mmGetFiles.mock.funcGetFiles != nil {
		mmGetFiles.mock.t.Fatalf("RepoMock.GetFiles mock is already set by Set")
	}

	if mmGetFiles.defaultExpectation == nil {
		mmGetFiles.defaultExpectation = &RepoMockGetFilesExpectation{mock: mmGetFiles.mock}
	}
	mmGetFiles.defaultExpectation.results = &RepoMockGetFilesResults{sa1, err}
	return mmGetFiles.mock
}

// Set uses given function f to mock the Repo.GetFiles method
func (mmGetFiles *mRepoMockGetFiles) Set(f func(ctx context.Context, revision models.Revision, dirs ...string) (sa1 []string, err error)) *RepoMock {
	if mmGetFiles.defaultExpectation != nil {
		mmGetFiles.mock.t.Fatalf("Default expectation is already set for the Repo.GetFiles method")
	}

	if len(mmGetFiles.expectations) > 0 {
		mmGetFiles.mock.t.Fatalf("Some expectations are already set for the Repo.GetFiles method")
	}

	mmGetFiles.mock.funcGetFiles = f
	return mmGetFiles.mock
}

// When sets expectation for the Repo.GetFiles which will trigger the result defined by the following
// Then helper
func (mmGetFiles *mRepoMockGetFiles) When(ctx context.Context, revision models.Revision, dirs ...string) *RepoMockGetFilesExpectation {
	if mmGetFiles.mock.funcGetFiles != nil {
		mmGetFiles.mock.t.Fatalf("RepoMock.GetFiles mock is already set by Set")
	}

	expectation := &RepoMockGetFilesExpectation{
		mock:   mmGetFiles.mock,
		params: &RepoMockGetFilesParams{ctx, revision, dirs},
	}
	mmGetFiles.expectations = append(mmGetFiles.expectations, expectation)
	return expectation
}

// Then sets up Repo.GetFiles return parameters for the expectation previously defined by the When method
func (e *RepoMockGetFilesExpectation) Then(sa1 []string, err error) *RepoMock {
	e.results = &RepoMockGetFilesResults{sa1, err}
	return e.mock
}

// GetFiles implements repository.Repo
func (mmGetFiles *RepoMock) GetFiles(ctx context.Context, revision models.Revision, dirs ...string) (sa1 []string, err error) {
	mm_atomic.AddUint64(&mmGetFiles.beforeGetFilesCounter, 1)
	defer mm_atomic.AddUint64(&mmGetFiles.afterGetFilesCounter, 1)

	if mmGetFiles.inspectFuncGetFiles != nil {
		mmGetFiles.inspectFuncGetFiles(ctx, revision, dirs...)
	}

	mm_params := &RepoMockGetFilesParams{ctx, revision, dirs}

	// Record call args
	mmGetFiles.GetFilesMock.mutex.Lock()
	mmGetFiles.GetFilesMock.callArgs = append(mmGetFiles.GetFilesMock.callArgs, mm_params)
	mmGetFiles.GetFilesMock.mutex.Unlock()

	for _, e := range mmGetFiles.GetFilesMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmGetFiles.GetFilesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetFiles.GetFilesMock.defaultExpectation.Counter, 1)
		mm_want := mmGetFiles.GetFilesMock.defaultExpectation.params
		mm_got := RepoMockGetFilesParams{ctx, revision, dirs}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetFiles.t.Errorf("RepoMock.GetFiles got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetFiles.GetFilesMock.defaultExpectation.results
		if mm_results == nil {
			mmGetFiles.t.Fatal("No results are set for the RepoMock.GetFiles")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmGetFiles.funcGetFiles != nil {
		return mmGetFiles.funcGetFiles(ctx, revision, dirs...)
	}
	mmGetFiles.t.Fatalf("Unexpected call to RepoMock.GetFiles. %v %v %v", ctx, revision, dirs)
	return
}

// GetFilesAfterCounter returns a count of finished RepoMock.GetFiles invocations
func (mmGetFiles *RepoMock) GetFilesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetFiles.afterGetFilesCounter)
}

// GetFilesBeforeCounter returns a count of RepoMock.GetFiles invocations
func (mmGetFiles *RepoMock) GetFilesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetFiles.beforeGetFilesCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.GetFiles.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetFiles *mRepoMockGetFiles) Calls() []*RepoMockGetFilesParams {
	mmGetFiles.mutex.RLock()

	argCopy := make([]*RepoMockGetFilesParams, len(mmGetFiles.callArgs))
	copy(argCopy, mmGetFiles.callArgs)

	mmGetFiles.mutex.RUnlock()

	return argCopy
}

// MinimockGetFilesDone returns true if the count of the GetFiles invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockGetFilesDone() bool {
	for _, e := range m.GetFilesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetFilesMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetFilesCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetFiles != nil && mm_atomic.LoadUint64(&m.afterGetFilesCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetFilesInspect logs each unmet expectation
func (m *RepoMock) MinimockGetFilesInspect() {
	for _, e := range m.GetFilesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.GetFiles with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetFilesMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetFilesCounter) < 1 {
		if m.GetFilesMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepoMock.GetFiles")
		} else {
			m.t.Errorf("Expected call to RepoMock.GetFiles with params: %#v", *m.GetFilesMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetFiles != nil && mm_atomic.LoadUint64(&m.afterGetFilesCounter) < 1 {
		m.t.Error("Expected call to RepoMock.GetFiles")
	}
}

type mRepoMockReadFile struct {
	mock               *RepoMock
	defaultExpectation *RepoMockReadFileExpectation
	expectations       []*RepoMockReadFileExpectation

	callArgs []*RepoMockReadFileParams
	mutex    sync.RWMutex
}

// RepoMockReadFileExpectation specifies expectation struct of the Repo.ReadFile
type RepoMockReadFileExpectation struct {
	mock    *RepoMock
	params  *RepoMockReadFileParams
	results *RepoMockReadFileResults
	Counter uint64
}

// RepoMockReadFileParams contains parameters of the Repo.ReadFile
type RepoMockReadFileParams struct {
	ctx      context.Context
	revision models.Revision
	fileName string
}

// RepoMockReadFileResults contains results of the Repo.ReadFile
type RepoMockReadFileResults struct {
	s1  string
	err error
}

// Expect sets up expected params for Repo.ReadFile
func (mmReadFile *mRepoMockReadFile) Expect(ctx context.Context, revision models.Revision, fileName string) *mRepoMockReadFile {
	if mmReadFile.mock.funcReadFile != nil {
		mmReadFile.mock.t.Fatalf("RepoMock.ReadFile mock is already set by Set")
	}

	if mmReadFile.defaultExpectation == nil {
		mmReadFile.defaultExpectation = &RepoMockReadFileExpectation{}
	}

	mmReadFile.defaultExpectation.params = &RepoMockReadFileParams{ctx, revision, fileName}
	for _, e := range mmReadFile.expectations {
		if minimock.Equal(e.params, mmReadFile.defaultExpectation.params) {
			mmReadFile.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmReadFile.defaultExpectation.params)
		}
	}

	return mmReadFile
}

// Inspect accepts an inspector function that has same arguments as the Repo.ReadFile
func (mmReadFile *mRepoMockReadFile) Inspect(f func(ctx context.Context, revision models.Revision, fileName string)) *mRepoMockReadFile {
	if mmReadFile.mock.inspectFuncReadFile != nil {
		mmReadFile.mock.t.Fatalf("Inspect function is already set for RepoMock.ReadFile")
	}

	mmReadFile.mock.inspectFuncReadFile = f

	return mmReadFile
}

// Return sets up results that will be returned by Repo.ReadFile
func (mmReadFile *mRepoMockReadFile) Return(s1 string, err error) *RepoMock {
	if mmReadFile.mock.funcReadFile != nil {
		mmReadFile.mock.t.Fatalf("RepoMock.ReadFile mock is already set by Set")
	}

	if mmReadFile.defaultExpectation == nil {
		mmReadFile.defaultExpectation = &RepoMockReadFileExpectation{mock: mmReadFile.mock}
	}
	mmReadFile.defaultExpectation.results = &RepoMockReadFileResults{s1, err}
	return mmReadFile.mock
}

// Set uses given function f to mock the Repo.ReadFile method
func (mmReadFile *mRepoMockReadFile) Set(f func(ctx context.Context, revision models.Revision, fileName string) (s1 string, err error)) *RepoMock {
	if mmReadFile.defaultExpectation != nil {
		mmReadFile.mock.t.Fatalf("Default expectation is already set for the Repo.ReadFile method")
	}

	if len(mmReadFile.expectations) > 0 {
		mmReadFile.mock.t.Fatalf("Some expectations are already set for the Repo.ReadFile method")
	}

	mmReadFile.mock.funcReadFile = f
	return mmReadFile.mock
}

// When sets expectation for the Repo.ReadFile which will trigger the result defined by the following
// Then helper
func (mmReadFile *mRepoMockReadFile) When(ctx context.Context, revision models.Revision, fileName string) *RepoMockReadFileExpectation {
	if mmReadFile.mock.funcReadFile != nil {
		mmReadFile.mock.t.Fatalf("RepoMock.ReadFile mock is already set by Set")
	}

	expectation := &RepoMockReadFileExpectation{
		mock:   mmReadFile.mock,
		params: &RepoMockReadFileParams{ctx, revision, fileName},
	}
	mmReadFile.expectations = append(mmReadFile.expectations, expectation)
	return expectation
}

// Then sets up Repo.ReadFile return parameters for the expectation previously defined by the When method
func (e *RepoMockReadFileExpectation) Then(s1 string, err error) *RepoMock {
	e.results = &RepoMockReadFileResults{s1, err}
	return e.mock
}

// ReadFile implements repository.Repo
func (mmReadFile *RepoMock) ReadFile(ctx context.Context, revision models.Revision, fileName string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmReadFile.beforeReadFileCounter, 1)
	defer mm_atomic.AddUint64(&mmReadFile.afterReadFileCounter, 1)

	if mmReadFile.inspectFuncReadFile != nil {
		mmReadFile.inspectFuncReadFile(ctx, revision, fileName)
	}

	mm_params := &RepoMockReadFileParams{ctx, revision, fileName}

	// Record call args
	mmReadFile.ReadFileMock.mutex.Lock()
	mmReadFile.ReadFileMock.callArgs = append(mmReadFile.ReadFileMock.callArgs, mm_params)
	mmReadFile.ReadFileMock.mutex.Unlock()

	for _, e := range mmReadFile.ReadFileMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmReadFile.ReadFileMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReadFile.ReadFileMock.defaultExpectation.Counter, 1)
		mm_want := mmReadFile.ReadFileMock.defaultExpectation.params
		mm_got := RepoMockReadFileParams{ctx, revision, fileName}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmReadFile.t.Errorf("RepoMock.ReadFile got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmReadFile.ReadFileMock.defaultExpectation.results
		if mm_results == nil {
			mmReadFile.t.Fatal("No results are set for the RepoMock.ReadFile")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmReadFile.funcReadFile != nil {
		return mmReadFile.funcReadFile(ctx, revision, fileName)
	}
	mmReadFile.t.Fatalf("Unexpected call to RepoMock.ReadFile. %v %v %v", ctx, revision, fileName)
	return
}

// ReadFileAfterCounter returns a count of finished RepoMock.ReadFile invocations
func (mmReadFile *RepoMock) ReadFileAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReadFile.afterReadFileCounter)
}

// ReadFileBeforeCounter returns a count of RepoMock.ReadFile invocations
func (mmReadFile *RepoMock) ReadFileBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReadFile.beforeReadFileCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.ReadFile.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmReadFile *mRepoMockReadFile) Calls() []*RepoMockReadFileParams {
	mmReadFile.mutex.RLock()

	argCopy := make([]*RepoMockReadFileParams, len(mmReadFile.callArgs))
	copy(argCopy, mmReadFile.callArgs)

	mmReadFile.mutex.RUnlock()

	return argCopy
}

// MinimockReadFileDone returns true if the count of the ReadFile invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockReadFileDone() bool {
	for _, e := range m.ReadFileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadFileMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadFileCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReadFile != nil && mm_atomic.LoadUint64(&m.afterReadFileCounter) < 1 {
		return false
	}
	return true
}

// MinimockReadFileInspect logs each unmet expectation
func (m *RepoMock) MinimockReadFileInspect() {
	for _, e := range m.ReadFileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.ReadFile with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadFileMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadFileCounter) < 1 {
		if m.ReadFileMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepoMock.ReadFile")
		} else {
			m.t.Errorf("Expected call to RepoMock.ReadFile with params: %#v", *m.ReadFileMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReadFile != nil && mm_atomic.LoadUint64(&m.afterReadFileCounter) < 1 {
		m.t.Error("Expected call to RepoMock.ReadFile")
	}
}

type mRepoMockReadRevision struct {
	mock               *RepoMock
	defaultExpectation *RepoMockReadRevisionExpectation
	expectations       []*RepoMockReadRevisionExpectation

	callArgs []*RepoMockReadRevisionParams
	mutex    sync.RWMutex
}

// RepoMockReadRevisionExpectation specifies expectation struct of the Repo.ReadRevision
type RepoMockReadRevisionExpectation struct {
	mock    *RepoMock
	params  *RepoMockReadRevisionParams
	results *RepoMockReadRevisionResults
	Counter uint64
}

// RepoMockReadRevisionParams contains parameters of the Repo.ReadRevision
type RepoMockReadRevisionParams struct {
	ctx              context.Context
	requestedVersion models.RequestedVersion
}

// RepoMockReadRevisionResults contains results of the Repo.ReadRevision
type RepoMockReadRevisionResults struct {
	r1  models.Revision
	err error
}

// Expect sets up expected params for Repo.ReadRevision
func (mmReadRevision *mRepoMockReadRevision) Expect(ctx context.Context, requestedVersion models.RequestedVersion) *mRepoMockReadRevision {
	if mmReadRevision.mock.funcReadRevision != nil {
		mmReadRevision.mock.t.Fatalf("RepoMock.ReadRevision mock is already set by Set")
	}

	if mmReadRevision.defaultExpectation == nil {
		mmReadRevision.defaultExpectation = &RepoMockReadRevisionExpectation{}
	}

	mmReadRevision.defaultExpectation.params = &RepoMockReadRevisionParams{ctx, requestedVersion}
	for _, e := range mmReadRevision.expectations {
		if minimock.Equal(e.params, mmReadRevision.defaultExpectation.params) {
			mmReadRevision.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmReadRevision.defaultExpectation.params)
		}
	}

	return mmReadRevision
}

// Inspect accepts an inspector function that has same arguments as the Repo.ReadRevision
func (mmReadRevision *mRepoMockReadRevision) Inspect(f func(ctx context.Context, requestedVersion models.RequestedVersion)) *mRepoMockReadRevision {
	if mmReadRevision.mock.inspectFuncReadRevision != nil {
		mmReadRevision.mock.t.Fatalf("Inspect function is already set for RepoMock.ReadRevision")
	}

	mmReadRevision.mock.inspectFuncReadRevision = f

	return mmReadRevision
}

// Return sets up results that will be returned by Repo.ReadRevision
func (mmReadRevision *mRepoMockReadRevision) Return(r1 models.Revision, err error) *RepoMock {
	if mmReadRevision.mock.funcReadRevision != nil {
		mmReadRevision.mock.t.Fatalf("RepoMock.ReadRevision mock is already set by Set")
	}

	if mmReadRevision.defaultExpectation == nil {
		mmReadRevision.defaultExpectation = &RepoMockReadRevisionExpectation{mock: mmReadRevision.mock}
	}
	mmReadRevision.defaultExpectation.results = &RepoMockReadRevisionResults{r1, err}
	return mmReadRevision.mock
}

// Set uses given function f to mock the Repo.ReadRevision method
func (mmReadRevision *mRepoMockReadRevision) Set(f func(ctx context.Context, requestedVersion models.RequestedVersion) (r1 models.Revision, err error)) *RepoMock {
	if mmReadRevision.defaultExpectation != nil {
		mmReadRevision.mock.t.Fatalf("Default expectation is already set for the Repo.ReadRevision method")
	}

	if len(mmReadRevision.expectations) > 0 {
		mmReadRevision.mock.t.Fatalf("Some expectations are already set for the Repo.ReadRevision method")
	}

	mmReadRevision.mock.funcReadRevision = f
	return mmReadRevision.mock
}

// When sets expectation for the Repo.ReadRevision which will trigger the result defined by the following
// Then helper
func (mmReadRevision *mRepoMockReadRevision) When(ctx context.Context, requestedVersion models.RequestedVersion) *RepoMockReadRevisionExpectation {
	if mmReadRevision.mock.funcReadRevision != nil {
		mmReadRevision.mock.t.Fatalf("RepoMock.ReadRevision mock is already set by Set")
	}

	expectation := &RepoMockReadRevisionExpectation{
		mock:   mmReadRevision.mock,
		params: &RepoMockReadRevisionParams{ctx, requestedVersion},
	}
	mmReadRevision.expectations = append(mmReadRevision.expectations, expectation)
	return expectation
}

// Then sets up Repo.ReadRevision return parameters for the expectation previously defined by the When method
func (e *RepoMockReadRevisionExpectation) Then(r1 models.Revision, err error) *RepoMock {
	e.results = &RepoMockReadRevisionResults{r1, err}
	return e.mock
}

// ReadRevision implements repository.Repo
func (mmReadRevision *RepoMock) ReadRevision(ctx context.Context, requestedVersion models.RequestedVersion) (r1 models.Revision, err error) {
	mm_atomic.AddUint64(&mmReadRevision.beforeReadRevisionCounter, 1)
	defer mm_atomic.AddUint64(&mmReadRevision.afterReadRevisionCounter, 1)

	if mmReadRevision.inspectFuncReadRevision != nil {
		mmReadRevision.inspectFuncReadRevision(ctx, requestedVersion)
	}

	mm_params := &RepoMockReadRevisionParams{ctx, requestedVersion}

	// Record call args
	mmReadRevision.ReadRevisionMock.mutex.Lock()
	mmReadRevision.ReadRevisionMock.callArgs = append(mmReadRevision.ReadRevisionMock.callArgs, mm_params)
	mmReadRevision.ReadRevisionMock.mutex.Unlock()

	for _, e := range mmReadRevision.ReadRevisionMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmReadRevision.ReadRevisionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReadRevision.ReadRevisionMock.defaultExpectation.Counter, 1)
		mm_want := mmReadRevision.ReadRevisionMock.defaultExpectation.params
		mm_got := RepoMockReadRevisionParams{ctx, requestedVersion}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmReadRevision.t.Errorf("RepoMock.ReadRevision got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmReadRevision.ReadRevisionMock.defaultExpectation.results
		if mm_results == nil {
			mmReadRevision.t.Fatal("No results are set for the RepoMock.ReadRevision")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmReadRevision.funcReadRevision != nil {
		return mmReadRevision.funcReadRevision(ctx, requestedVersion)
	}
	mmReadRevision.t.Fatalf("Unexpected call to RepoMock.ReadRevision. %v %v", ctx, requestedVersion)
	return
}

// ReadRevisionAfterCounter returns a count of finished RepoMock.ReadRevision invocations
func (mmReadRevision *RepoMock) ReadRevisionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReadRevision.afterReadRevisionCounter)
}

// ReadRevisionBeforeCounter returns a count of RepoMock.ReadRevision invocations
func (mmReadRevision *RepoMock) ReadRevisionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReadRevision.beforeReadRevisionCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.ReadRevision.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmReadRevision *mRepoMockReadRevision) Calls() []*RepoMockReadRevisionParams {
	mmReadRevision.mutex.RLock()

	argCopy := make([]*RepoMockReadRevisionParams, len(mmReadRevision.callArgs))
	copy(argCopy, mmReadRevision.callArgs)

	mmReadRevision.mutex.RUnlock()

	return argCopy
}

// MinimockReadRevisionDone returns true if the count of the ReadRevision invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockReadRevisionDone() bool {
	for _, e := range m.ReadRevisionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadRevisionMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadRevisionCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReadRevision != nil && mm_atomic.LoadUint64(&m.afterReadRevisionCounter) < 1 {
		return false
	}
	return true
}

// MinimockReadRevisionInspect logs each unmet expectation
func (m *RepoMock) MinimockReadRevisionInspect() {
	for _, e := range m.ReadRevisionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.ReadRevision with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadRevisionMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadRevisionCounter) < 1 {
		if m.ReadRevisionMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepoMock.ReadRevision")
		} else {
			m.t.Errorf("Expected call to RepoMock.ReadRevision with params: %#v", *m.ReadRevisionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReadRevision != nil && mm_atomic.LoadUint64(&m.afterReadRevisionCounter) < 1 {
		m.t.Error("Expected call to RepoMock.ReadRevision")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepoMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockArchiveInspect()

		m.MinimockFetchInspect()

		m.MinimockGetFilesInspect()

		m.MinimockReadFileInspect()

		m.MinimockReadRevisionInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockArchiveDone() &&
		m.MinimockFetchDone() &&
		m.MinimockGetFilesDone() &&
		m.MinimockReadFileDone() &&
		m.MinimockReadRevisionDone()
}
