package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"go.redsock.ru/moti/internal/adapters/repository"
	"go.redsock.ru/moti/internal/adapters/repository/git"
)

// RepoFactoryMock implements install.RepoFactory
type RepoFactoryMock struct {
	t minimock.Tester

	funcNew          func(ctx context.Context, remote string, cacheDir string, console git.Console) (r1 repository.Repo, err error)
	inspectFuncNew   func(ctx context.Context, remote string, cacheDir string, console git.Console)
	afterNewCounter  uint64
	beforeNewCounter uint64
	NewMock          mRepoFactoryMockNew
}

// NewRepoFactoryMock returns a mock for install.RepoFactory
func NewRepoFactoryMock(t minimock.Tester) *RepoFactoryMock {
	m := &RepoFactoryMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.NewMock = mRepoFactoryMockNew{mock: m}
	m.NewMock.callArgs = []*RepoFactoryMockNewParams{}

	return m
}

type mRepoFactoryMockNew struct {
	mock               *RepoFactoryMock
	defaultExpectation *RepoFactoryMockNewExpectation
	expectations       []*RepoFactoryMockNewExpectation

	callArgs []*RepoFactoryMockNewParams
	mutex    sync.RWMutex
}

// RepoFactoryMockNewExpectation specifies expectation struct of the RepoFactory.New
type RepoFactoryMockNewExpectation struct {
	mock    *RepoFactoryMock
	params  *RepoFactoryMockNewParams
	results *RepoFactoryMockNewResults
	Counter uint64
}

// RepoFactoryMockNewParams contains parameters of the RepoFactory.New
type RepoFactoryMockNewParams struct {
	ctx      context.Context
	remote   string
	cacheDir string
	console  git.Console
}

// RepoFactoryMockNewResults contains results of the RepoFactory.New
type RepoFactoryMockNewResults struct {
	r1  repository.Repo
	err error
}

// Expect sets up expected params for RepoFactory.New
func (mmNew *mRepoFactoryMockNew) Expect(ctx context.Context, remote string, cacheDir string, console git.Console) *mRepoFactoryMockNew {
	if mmNew.mock.funcNew != nil {
		mmNew.mock.t.Fatalf("RepoFactoryMock.New mock is already set by Set")
	}

	if mmNew.defaultExpectation == nil {
		mmNew.defaultExpectation = &RepoFactoryMockNewExpectation{}
	}

	mmNew.defaultExpectation.params = &RepoFactoryMockNewParams{ctx, remote, cacheDir, console}
	for _, e := range mmNew.expectations {
		if minimock.Equal(e.params, mmNew.defaultExpectation.params) {
			mmNew.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmNew.defaultExpectation.params)
		}
	}

	return mmNew
}

// Inspect accepts an inspector function that has same arguments as the RepoFactory.New
func (mmNew *mRepoFactoryMockNew) Inspect(f func(ctx context.Context, remote string, cacheDir string, console git.Console)) *mRepoFactoryMockNew {
	if mmNew.mock.inspectFuncNew != nil {
		mmNew.mock.t.Fatalf("Inspect function is already set for RepoFactoryMock.New")
	}

	mmNew.mock.inspectFuncNew = f

	return mmNew
}

// Return sets up results that will be returned by RepoFactory.New
func (mmNew *mRepoFactoryMockNew) Return(r1 repository.Repo, err error) *RepoFactoryMock {
	if mmNew.mock.funcNew != nil {
		mmNew.mock.t.Fatalf("RepoFactoryMock.New mock is already set by Set")
	}

	if mmNew.defaultExpectation == nil {
		mmNew.defaultExpectation = &RepoFactoryMockNewExpectation{mock: mmNew.mock}
	}
	mmNew.defaultExpectation.results = &RepoFactoryMockNewResults{r1, err}
	return mmNew.mock
}

// Set uses given function f to mock the RepoFactory.New method
func (mmNew *mRepoFactoryMockNew) Set(f func(ctx context.Context, remote string, cacheDir string, console git.Console) (r1 repository.Repo, err error)) *RepoFactoryMock {
	if mmNew.defaultExpectation != nil {
		mmNew.mock.t.Fatalf("Default expectation is already set for the RepoFactory.New method")
	}

	if len(mmNew.expectations) > 0 {
		mmNew.mock.t.Fatalf("Some expectations are already set for the RepoFactory.New method")
	}

	mmNew.mock.funcNew = f
	return mmNew.mock
}

// When sets expectation for the RepoFactory.New which will trigger the result defined by the following
// Then helper
func (mmNew *mRepoFactoryMockNew) When(ctx context.Context, remote string, cacheDir string, console git.Console) *RepoFactoryMockNewExpectation {
	if mmNew.mock.funcNew != nil {
		mmNew.mock.t.Fatalf("RepoFactoryMock.New mock is already set by Set")
	}

	expectation := &RepoFactoryMockNewExpectation{
		mock:   mmNew.mock,
		params: &RepoFactoryMockNewParams{ctx, remote, cacheDir, console},
	}
	mmNew.expectations = append(mmNew.expectations, expectation)
	return expectation
}

// Then sets up RepoFactory.New return parameters for the expectation previously defined by the When method
func (e *RepoFactoryMockNewExpectation) Then(r1 repository.Repo, err error) *RepoFactoryMock {
	e.results = &RepoFactoryMockNewResults{r1, err}
	return e.mock
}

// New implements install.RepoFactory
func (mmNew *RepoFactoryMock) New(ctx context.Context, remote string, cacheDir string, console git.Console) (r1 repository.Repo, err error) {
	mm_atomic.AddUint64(&mmNew.beforeNewCounter, 1)
	defer mm_atomic.AddUint64(&mmNew.afterNewCounter, 1)

	if mmNew.inspectFuncNew != nil {
		mmNew.inspectFuncNew(ctx, remote, cacheDir, console)
	}

	mm_params := &RepoFactoryMockNewParams{ctx, remote, cacheDir, console}

	// Record call args
	mmNew.NewMock.mutex.Lock()
	mmNew.NewMock.callArgs = append(mmNew.NewMock.callArgs, mm_params)
	mmNew.NewMock.mutex.Unlock()

	for _, e := range mmNew.NewMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmNew.NewMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNew.NewMock.defaultExpectation.Counter, 1)
		mm_want := mmNew.NewMock.defaultExpectation.params
		mm_got := RepoFactoryMockNewParams{ctx, remote, cacheDir, console}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmNew.t.Errorf("RepoFactoryMock.New got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmNew.NewMock.defaultExpectation.results
		if mm_results == nil {
			mmNew.t.Fatal("No results are set for the RepoFactoryMock.New")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmNew.funcNew != nil {
		return mmNew.funcNew(ctx, remote, cacheDir, console)
	}
	mmNew.t.Fatalf("Unexpected call to RepoFactoryMock.New. %v %v %v %v", ctx, remote, cacheDir, console)
	return
}

// NewAfterCounter returns a count of finished RepoFactoryMock.New invocations
func (mmNew *RepoFactoryMock) NewAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNew.afterNewCounter)
}

// NewBeforeCounter returns a count of RepoFactoryMock.New invocations
func (mmNew *RepoFactoryMock) NewBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNew.beforeNewCounter)
}

// Calls returns a list of arguments used in each call to RepoFactoryMock.New.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmNew *mRepoFactoryMockNew) Calls() []*RepoFactoryMockNewParams {
	mmNew.mutex.RLock()

	argCopy := make([]*RepoFactoryMockNewParams, len(mmNew.callArgs))
	copy(argCopy, mmNew.callArgs)

	mmNew.mutex.RUnlock()

	return argCopy
}

// MinimockNewDone returns true if the count of the New invocations corresponds
// the number of defined expectations
func (m *RepoFactoryMock) MinimockNewDone() bool {
	for _, e := range m.NewMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.NewMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterNewCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNew != nil && mm_atomic.LoadUint64(&m.afterNewCounter) < 1 {
		return false
	}
	return true
}

// MinimockNewInspect logs each unmet expectation
func (m *RepoFactoryMock) MinimockNewInspect() {
	for _, e := range m.NewMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoFactoryMock.New with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.NewMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterNewCounter) < 1 {
		if m.NewMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepoFactoryMock.New")
		} else {
			m.t.Errorf("Expected call to RepoFactoryMock.New with params: %#v", *m.NewMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNew != nil && mm_atomic.LoadUint64(&m.afterNewCounter) < 1 {
		m.t.Error("Expected call to RepoFactoryMock.New")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepoFactoryMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockNewInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepoFactoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepoFactoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockNewDone()
}
