// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: basic_service.proto

package basic_example_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BasicExampleApi_Hello_FullMethodName = "/basic_example_api.BasicExampleApi/Hello"
)

// BasicExampleApiClient is the client API for BasicExampleApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BasicExampleApiClient interface {
	Hello(ctx context.Context, in *Hello_Request, opts ...grpc.CallOption) (*Hello_Response, error)
}

type basicExampleApiClient struct {
	cc grpc.ClientConnInterface
}

func NewBasicExampleApiClient(cc grpc.ClientConnInterface) BasicExampleApiClient {
	return &basicExampleApiClient{cc}
}

func (c *basicExampleApiClient) Hello(ctx context.Context, in *Hello_Request, opts ...grpc.CallOption) (*Hello_Response, error) {
	out := new(Hello_Response)
	err := c.cc.Invoke(ctx, BasicExampleApi_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasicExampleApiServer is the server API for BasicExampleApi service.
// All implementations must embed UnimplementedBasicExampleApiServer
// for forward compatibility
type BasicExampleApiServer interface {
	Hello(context.Context, *Hello_Request) (*Hello_Response, error)
	mustEmbedUnimplementedBasicExampleApiServer()
}

// UnimplementedBasicExampleApiServer must be embedded to have forward compatible implementations.
type UnimplementedBasicExampleApiServer struct {
}

func (UnimplementedBasicExampleApiServer) Hello(context.Context, *Hello_Request) (*Hello_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedBasicExampleApiServer) mustEmbedUnimplementedBasicExampleApiServer() {}

// UnsafeBasicExampleApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BasicExampleApiServer will
// result in compilation errors.
type UnsafeBasicExampleApiServer interface {
	mustEmbedUnimplementedBasicExampleApiServer()
}

func RegisterBasicExampleApiServer(s grpc.ServiceRegistrar, srv BasicExampleApiServer) {
	s.RegisterService(&BasicExampleApi_ServiceDesc, srv)
}

func _BasicExampleApi_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasicExampleApiServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasicExampleApi_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasicExampleApiServer).Hello(ctx, req.(*Hello_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// BasicExampleApi_ServiceDesc is the grpc.ServiceDesc for BasicExampleApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BasicExampleApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basic_example_api.BasicExampleApi",
	HandlerType: (*BasicExampleApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _BasicExampleApi_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basic_service.proto",
}
