// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: basic_service.proto

package basic_example_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_basic_service_proto protoreflect.FileDescriptor

const file_basic_service_proto_rawDesc = "" +
	"\n" +
	"\x13basic_service.proto\x12\x11basic_example_api\x1a\x1cgoogle/api/annotations.proto\x1a\x0emessages.proto2s\n" +
	"\x0fBasicExampleApi\x12`\n" +
	"\x05Hello\x12 .basic_example_api.Hello.Request\x1a!.basic_example_api.Hello.Response\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/helloBAZ?go.redsock.ru/moti/examples/basic_example_api;basic_example_apib\x06proto3"

var file_basic_service_proto_goTypes = []any{
	(*Hello_Request)(nil),  // 0: basic_example_api.Hello.Request
	(*Hello_Response)(nil), // 1: basic_example_api.Hello.Response
}
var file_basic_service_proto_depIdxs = []int32{
	0, // 0: basic_example_api.BasicExampleApi.Hello:input_type -> basic_example_api.Hello.Request
	1, // 1: basic_example_api.BasicExampleApi.Hello:output_type -> basic_example_api.Hello.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_basic_service_proto_init() }
func file_basic_service_proto_init() {
	if File_basic_service_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_service_proto_rawDesc), len(file_basic_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basic_service_proto_goTypes,
		DependencyIndexes: file_basic_service_proto_depIdxs,
	}.Build()
	File_basic_service_proto = out.File
	file_basic_service_proto_goTypes = nil
	file_basic_service_proto_depIdxs = nil
}
