// Code generated by ogen, DO NOT EDIT.

package todos

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateTodoOperation OperationName = "CreateTodo"
	DeleteTodoOperation OperationName = "DeleteTodo"
	GetTodoOperation    OperationName = "GetTodo"
	ListTodosOperation  OperationName = "ListTodos"
	UpdateTodoOperation OperationName = "UpdateTodo"
)
