// Code generated by ogen, DO NOT EDIT.
package todos

type DeleteTodoRes interface {
	deleteTodoRes()
}

type GetTodoRes interface {
	getTodoRes()
}

type UpdateTodoRes interface {
	updateTodoRes()
}
