// Code generated by ogen, DO NOT EDIT.

package todos

// Ref: #/components/schemas/CreateTodoRequest
type CreateTodoRequest struct {
	Title string `json:"title"`
}

// GetTitle returns the value of Title.
func (s *CreateTodoRequest) GetTitle() string {
	return s.Title
}

// SetTitle sets the value of Title.
func (s *CreateTodoRequest) SetTitle(val string) {
	s.Title = val
}

// DeleteTodoNoContent is response for DeleteTodo operation.
type DeleteTodoNoContent struct{}

func (*DeleteTodoNoContent) deleteTodoRes() {}

// DeleteTodoNotFound is response for DeleteTodo operation.
type DeleteTodoNotFound struct{}

func (*DeleteTodoNotFound) deleteTodoRes() {}

// GetTodoNotFound is response for GetTodo operation.
type GetTodoNotFound struct{}

func (*GetTodoNotFound) getTodoRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Todo
type Todo struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}

// GetID returns the value of ID.
func (s *Todo) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Todo) GetTitle() string {
	return s.Title
}

// GetDone returns the value of Done.
func (s *Todo) GetDone() bool {
	return s.Done
}

// SetID sets the value of ID.
func (s *Todo) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Todo) SetTitle(val string) {
	s.Title = val
}

// SetDone sets the value of Done.
func (s *Todo) SetDone(val bool) {
	s.Done = val
}

func (*Todo) getTodoRes()    {}
func (*Todo) updateTodoRes() {}

// UpdateTodoNotFound is response for UpdateTodo operation.
type UpdateTodoNotFound struct{}

func (*UpdateTodoNotFound) updateTodoRes() {}

// Ref: #/components/schemas/UpdateTodoRequest
type UpdateTodoRequest struct {
	Title OptString `json:"title"`
	Done  OptBool   `json:"done"`
}

// GetTitle returns the value of Title.
func (s *UpdateTodoRequest) GetTitle() OptString {
	return s.Title
}

// GetDone returns the value of Done.
func (s *UpdateTodoRequest) GetDone() OptBool {
	return s.Done
}

// SetTitle sets the value of Title.
func (s *UpdateTodoRequest) SetTitle(val OptString) {
	s.Title = val
}

// SetDone sets the value of Done.
func (s *UpdateTodoRequest) SetDone(val OptBool) {
	s.Done = val
}
