// Code generated by ogen, DO NOT EDIT.

package todos

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTodo implements createTodo operation.
//
// Create a todo.
//
// POST /todos
func (UnimplementedHandler) CreateTodo(ctx context.Context, req *CreateTodoRequest) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTodo implements deleteTodo operation.
//
// Delete a todo.
//
// DELETE /todos/{id}
func (UnimplementedHandler) DeleteTodo(ctx context.Context, params DeleteTodoParams) (r DeleteTodoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTodo implements getTodo operation.
//
// Get a todo by ID.
//
// GET /todos/{id}
func (UnimplementedHandler) GetTodo(ctx context.Context, params GetTodoParams) (r GetTodoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTodos implements listTodos operation.
//
// List all todos.
//
// GET /todos
func (UnimplementedHandler) ListTodos(ctx context.Context) (r []Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTodo implements updateTodo operation.
//
// Update a todo.
//
// PUT /todos/{id}
func (UnimplementedHandler) UpdateTodo(ctx context.Context, req *UpdateTodoRequest, params UpdateTodoParams) (r UpdateTodoRes, _ error) {
	return r, ht.ErrNotImplemented
}
