// Code generated by ogen, DO NOT EDIT.

package todos

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateTodo implements createTodo operation.
	//
	// Create a todo.
	//
	// POST /todos
	CreateTodo(ctx context.Context, req *CreateTodoRequest) (*Todo, error)
	// DeleteTodo implements deleteTodo operation.
	//
	// Delete a todo.
	//
	// DELETE /todos/{id}
	DeleteTodo(ctx context.Context, params DeleteTodoParams) (DeleteTodoRes, error)
	// GetTodo implements getTodo operation.
	//
	// Get a todo by ID.
	//
	// GET /todos/{id}
	GetTodo(ctx context.Context, params GetTodoParams) (GetTodoRes, error)
	// ListTodos implements listTodos operation.
	//
	// List all todos.
	//
	// GET /todos
	ListTodos(ctx context.Context) ([]Todo, error)
	// UpdateTodo implements updateTodo operation.
	//
	// Update a todo.
	//
	// PUT /todos/{id}
	UpdateTodo(ctx context.Context, req *UpdateTodoRequest, params UpdateTodoParams) (UpdateTodoRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
